Vincit/VISDOM-Roadmapper

- frontend/src/components/RoadmapSelectorWidget.tsx
- frontend/src/components/UserHotSwapWidget.tsx
- frontend/src/components/forms/Dropdown.module.scss
- frontend/src/components/forms/Dropdown.tsx
- frontend/src/shared.scss
Previously the current user was not displayed when there were no
hotSwappableUsers available.
Also removed some redundant checks.
> Always show the user next to "viewing as"

- frontend/src/components/TaskValueCreatedVisualization.tsx
- frontend/src/shared.scss
Reapplies:
ccf764408d8b86bc1f91c385354f06e2269c9b04
c98d6383e2ab122425a3a13676f800744e5c5b2a
aa46cc34442a0c40152f5a8c3cafbaf848328950
which were dropped in
a3753c1842c5c5676793e29c3247410f2a2e3b51
> Tooltip styles

- frontend/src/components/PlannerPageNavbar.module.scss
- frontend/src/components/PlannerPageNavbar.tsx
- frontend/src/pages/RoadmapGraphPage.module.scss
- frontend/src/pages/RoadmapGraphPage.tsx
Style changes to planner page's navbar and roadmap graph
> Planner page styles

- frontend/src/api/api.tsx
- frontend/src/components/NavBar.tsx
- frontend/src/i18/english.ts
- frontend/src/pages/RegisterPage.module.scss
- frontend/src/pages/RegisterPage.tsx
- frontend/src/redux/user/actions.ts
- frontend/src/redux/user/index.ts
- frontend/src/redux/user/types.ts
- frontend/src/routers/MainRouter.tsx
- frontend/src/routers/paths.ts
View for registration page and translations
> Register page

- frontend/src/pages/MilestonesEditor.tsx
- server/src/api/versions/versions.controller.ts
Milestone tasks are no longer deleted after milestone's order
is changed.
> Fix milestone dragging

- frontend/.eslintrc.js
- frontend/src/components/RoadmapSidebar.module.scss
- frontend/src/components/modals/AddJiraConfigurationModal.tsx
- frontend/src/components/modals/EditJiraConfigurationModal.tsx
- frontend/src/pages/MilestonesEditor.module.scss
- frontend/src/pages/TimeEstimationPage.tsx
- frontend/src/routers/paths.ts
Changed uses of IBM Plex Mono to pre-title typography (uses Anonymous Pro)
IBM Plex Mono is still found in TaskHeatmap (axis numbers) and TimeEstimationPage, which have not yet had style overhaul.
> Fix old fonts

- frontend/src/components/LoginNavBar.module.scss
- frontend/src/components/LoginNavBar.tsx
- frontend/src/components/NavBar.module.scss
- frontend/src/components/NavBar.tsx
- frontend/src/components/NavLayout.module.scss
- frontend/src/components/NavLayout.tsx
- frontend/src/global.scss
- frontend/src/pages/LandingPage.tsx
The navbar in landing, login & register pages will disappear and reappear in response to user scroll.
In landing page clicking the Visdom logo will scroll the page to its top: added this since the logo has functionality in login & register pages too
> Add responsive navbar

- frontend/src/components/LoginNavBar.module.scss
- frontend/src/components/LoginNavBar.tsx
- frontend/src/components/NavLayout.module.scss
- frontend/src/components/NavLayout.tsx
- frontend/src/global.scss
Navbar will stay at the start of the page, regardless of user input
> Remove responsive navbar

- server/src/api/users/users.model.ts
- server/src/migrations/20210525145930_caseInsensitiveUsernameAndEmail.ts
- server/src/utils/auth.ts
- server/tests/users.test.ts
- login accepts either username or email
- username and email are compared case insensitively
- '@' is disallowed in usernames
> Login with name or email

- frontend/src/api/api.tsx
- server/src/api/jira/jira.controller.ts
- server/src/api/tasks/tasks.model.ts
Also fixed few issues in jira routes:
- urls in frontend api
- roadmapId to Number
- transaction in importBoard
> Timestamp format validation

- frontend/src/components/RoadmapSelectorWidget.tsx
- frontend/src/pages/HomePage.tsx
User will be redirected to the dashboard of their latest opened roadmap after logging in.
> Add redirect after login

- frontend/src/pages/HomePage.tsx
NavLayout is already added in MainRouter
> Remove duplicate NavLayout

- frontend/src/components/RatingBars.tsx
- frontend/src/components/TaskRatingWidget.tsx
- frontend/src/components/modals/AddTaskModal.tsx
- frontend/src/components/modals/RateTaskModal.module.scss
- frontend/src/components/modals/RateTaskModal.tsx
- frontend/src/redux/user/types.ts
- server/src/api/users/users.controller.ts
- server/src/seeds/testdata.ts
- server/src/utils/auth.ts
- if user is developer
- a single slider for work estimate is shown
- otherwise if user represents customers
- value rating slider for each of the customers is shown
> Task rating for customers

- frontend/src/components/UserInfoCard.tsx
- frontend/src/redux/user/index.ts
- frontend/src/redux/user/reducers.ts
- frontend/src/redux/user/selectors.ts
- frontend/src/redux/user/types.ts
- server/src/utils/errorhandler.ts
Removed unnecessary loggedIn boolean from state.
Added cleanup for column names, after few constraints started using calculated columns.
> Cleanup state & error messages

- frontend/src/pages/DashboardPage.tsx
- server/knexfile.ts
- server/src/api/customer/customer.controller.ts
- server/src/server.ts
- server/src/types/customTypes.ts
Also non-null asserted env variables to make linter happy.
Removed plannerchart rendering from non-admins since it cannot be rendered without customer value information
> Secure customervalue behind permission

- frontend/src/components/modals/EditCustomerModal.module.scss
- frontend/src/components/modals/EditCustomerModal.tsx
"Pick a color" is now the default option and undefined colors are not passed to the color picker.
Checkbox css fixed
> Fix customer edition modal

- frontend/src/components/Dot.tsx
- frontend/src/components/TableTaskRow.module.scss
- frontend/src/components/TableTaskRow.tsx
- frontend/src/components/TaskTable.tsx
- frontend/src/components/modals/RateTaskModal.tsx
Show icons for missing task-ratings
> Show icons for missing task-ratings

- frontend/src/pages/MilestonesEditor.tsx
Tehty missing-task-ratings haaran päälle, kaikki planner-check-ratingsiin liittyvät muutokset tiedostossa 'frontend/src/pages/MilestonesEditor.tsx'
> Planner check ratings

- frontend/src/colors.module.scss
- frontend/src/components/forms/Checkbox.tsx
- frontend/src/components/forms/RadioButton.tsx
- frontend/src/components/forms/Slider.tsx
- frontend/src/pages/PlannerWeightsPage.module.scss
- frontend/src/pages/PlannerWeightsPage.tsx
- frontend/src/pages/RegisterPage.tsx
- frontend/src/shared.scss
Sliderin tyylit päivitetty ja listaan lisätty customerin väri
> Update client weights styles according to figma

- frontend/src/api/api.tsx
- frontend/src/components/RoadmapSidebar.tsx
- frontend/src/components/TableCustomerRow.tsx
- frontend/src/components/TableTaskRow.tsx
- frontend/src/components/TableTeamMemberRow.tsx
- frontend/src/components/TaskRatingWidget.tsx
- frontend/src/components/TaskTable.tsx
- frontend/src/components/UserInfoCard.tsx
- frontend/src/components/modals/RateTaskModal.tsx
- frontend/src/pages/ConfigurationPage.tsx
- frontend/src/pages/DashboardPage.tsx
- frontend/src/pages/RegisterPage.tsx
- frontend/src/redux/roadmaps/actions.ts
- frontend/src/redux/roadmaps/index.ts
- frontend/src/redux/roadmaps/reducers.ts
- frontend/src/redux/roadmaps/types.ts
- frontend/src/redux/user/actions.ts
- frontend/src/redux/user/types.ts
- frontend/src/utils/UserUtils.ts
- server/src/api/roadmaps/roadmaps.controller.ts
- server/src/api/roadmaps/roadmaps.routes.ts
- server/src/api/users/users.controller.ts
- server/src/api/users/users.model.ts
- server/src/migrations/20210618132417_removeUserType.ts
- server/src/seeds/testdata.ts
- server/src/utils/auth.ts
- server/tests/roadmaps.test.ts
- server/tests/roles.test.ts
- server/tests/users.test.ts
- shared/types/customTypes.ts
Käyttäjän UserInfon type on muutettu RoleTypeksi. Huom. type voi olla undefined, jos roadmappia ei ole valittu.
Dashboardilla haetaan käyttäjän info uudelleen, sillä ensimmäisessä kutsussa roadmappia ei ole valittu. Tämä tehdään myös kun roadmap vaihdetaan, jolloin oikea rooli päivittyy. Turhia kutsuja tästä kuitenkin tulee, sillä triggeri on vain dashboardille siirtyminen... en vielä keksinyt optimaalisempaa tapaa pyyntöjen lähetykseen.
Backendistä User-mallista on poistettu tyyppi.
> UserType to RoleType

- frontend/src/components/TableTaskRow.tsx
- frontend/src/components/TaskTable.module.scss
- frontend/src/components/TaskTable.tsx
- frontend/src/pages/MilestonesEditor.tsx
Kaikista taskeista erotellaan ensin huomiota vaativat (ei-arvioidut) taskit ja sitten loput taskit laitetaan toiseen taulukkoon.
> Add separate tables for rated and unrated tasks

- frontend/src/components/modals/EditCustomerModal.tsx
- frontend/src/redux/roadmaps/types.ts
- frontend/src/utils/CustomerUtils.ts
- server/src/api/customer/customer.model.ts
- server/src/migrations/20210630154740_requireCustomerEmail.ts
- server/src/seeds/testdata.ts
Changed customer email to be required in backend and modified a few things relating to customers (test data, customer edition "confirm" button)
> Require customer email

- frontend/src/components/TaskRatingWidget.module.scss
- frontend/src/components/TaskRatingWidget.tsx
- frontend/src/components/forms/FormField.module.scss
- frontend/src/components/forms/FormField.tsx
- frontend/src/components/modals/AddTaskModal.tsx
- frontend/src/components/modals/AddVersionModal.tsx
- frontend/src/components/modals/EditTaskModal.tsx
- frontend/src/components/modals/EditVersionModal.tsx
- frontend/src/components/modals/IntegrationConfigurationModal.tsx
- frontend/src/components/modals/IntegrationOauthModal.tsx
- frontend/src/components/modals/modalparts/CustomerModalParts.tsx
- frontend/src/pages/LoginPage.module.scss
- frontend/src/pages/LoginPage.tsx
- frontend/src/pages/RegisterPage.module.scss
- frontend/src/pages/RegisterPage.tsx
- frontend/src/shared.scss
The component wraps:
- optional label
- input element
- error message for the input
> Add component for form fields

- frontend/src/components/PlannerChart.module.scss
- frontend/src/components/PlannerChart.tsx
- frontend/src/components/RoadmapCompletionMeter.module.scss
- frontend/src/components/RoadmapSelectorWidget.module.scss
- frontend/src/components/TaskHeatmap.module.scss
- frontend/src/components/TaskRatingWidget.module.scss
- frontend/src/components/TaskRatingWidget.tsx
- frontend/src/components/TeamMemberListTable.tsx
- frontend/src/components/forms/Checkbox.module.scss
- frontend/src/components/forms/RadioButton.module.scss
- frontend/src/components/modals/AddCustomerModal.tsx
- frontend/src/components/modals/EditCustomerModal.tsx
- frontend/src/components/modals/EditTeamMemberModal.module.scss
- frontend/src/components/modals/RemovePeopleModal.tsx
- frontend/src/components/modals/TaskInfoModal.module.scss
- frontend/src/components/modals/TaskRatingsInfoModal.module.scss
- frontend/src/components/modals/modalparts/StepIndicator.tsx
- frontend/src/pages/ConfigurationPage.module.scss
- frontend/src/pages/LoginPage.module.scss
- frontend/src/pages/NotFoundPage.module.scss
- frontend/src/pages/PeopleListPage.tsx
- frontend/src/pages/RegisterPage.module.scss
- frontend/src/pages/TimeEstimationPage.module.scss
- frontend/src/shared.scss
Each commit's changes were small enough, so they were combined to this pr.
Fixups:
- Customer modals fetch userInfo
- 'Show completed tasks' checkbox works now as it's supposed to
- Add search to team members
- Style changes
Refactored StepIndicator
> Small fixups and a refactor

- frontend/package.json
- frontend/src/index.tsx
- frontend/src/pages/DashboardPage.module.scss
- frontend/src/pages/DashboardPage.tsx
- frontend/src/pages/TimeEstimationPage.module.scss
- frontend/yarn.lock
- styled-components
- @types/styled-components
- @types/styled-react-modal
- typeface-ibm-plex-mono
> Remove few unused dependencies

- server/src/api/customer/customer.controller.ts
Fix an issue where occasionally customer could get corrupted in the controller, causing the updating customers to stop working
> Fix occasional customer corruption on update

- server/src/migrations/20210713135033_addRoadmapIdCascadeOnDelete.ts
- server/src/seeds/testdata.ts
- server/src/utils/testdataUtils.ts
- server/tests/roles.test.ts
- server/tests/taskratings.test.ts
- server/tests/tasks.test.ts
Summarized the changes in the commit message.
Do comment if I missed any useful test data!
> Extend initial test data

- frontend/src/components/RoadmapSelectorWidget.module.scss
- frontend/src/components/forms/Checkbox.module.scss
- frontend/src/components/forms/Checkbox.tsx
- frontend/src/components/forms/RadioButton.module.scss
- frontend/src/components/forms/RadioButton.tsx
- frontend/src/components/modals/modalparts/StepIndicator.module.scss
- frontend/src/components/modals/modalparts/StepIndicator.tsx
- frontend/src/pages/RoadmapGraphPage.module.scss
- frontend/src/shared.scss
Buttons now have focus effects (incl. stepIndicator, dropdown).
Removed the extra focusable element on Checkboxes and radio buttons.
It was hard to notice the small outlined button was focused on, so I added a background color to focus/hover. Not sure if it's the most fitting solution, feedback is welcome
Keyboard navigation seemed ok to me.
> Fix button styles

- frontend/src/components/NavBar.module.scss
- frontend/src/components/ProjectSummary.tsx
- frontend/src/components/TableUnratedTaskRow.tsx
- frontend/src/index.tsx
StylesProvider ables overriding of Material-UI's styles. It is added to App root so styles can be overridden easier.
> Add StylesProvider to App

- frontend/src/components/CustomerListTable.tsx
- frontend/src/components/PlannerChart.tsx
- frontend/src/components/ProjectSummary.tsx
- frontend/src/components/TableUnratedTaskRow.tsx
- frontend/src/components/TaskValueCreatedVisualization.tsx
- frontend/src/components/modals/AddCustomerModal.tsx
- frontend/src/components/modals/EditCustomerModal.tsx
- frontend/src/pages/MilestonesEditor.tsx
- frontend/src/pages/PlannerWeightsPage.tsx
- frontend/src/pages/RoadmapGraphPage.tsx
- frontend/src/redux/roadmaps/actions.ts
- frontend/src/redux/roadmaps/selectors.ts
- frontend/src/routers/RoadmapRouter.tsx
Customers can be selected by the id of a roadmap in addition to the
selected/current roadmap id in redux.
Customers from other roadmaps can be fetched in frontend api.
> Modify frontend customers

- frontend/src/api/api.tsx
- frontend/src/components/ProjectSummary.tsx
- frontend/src/components/TableUnratedTaskRow.tsx
- frontend/src/components/TaskTable.tsx
- frontend/src/components/TeamMemberListTable.tsx
- frontend/src/components/modals/AddCustomerModal.tsx
- frontend/src/components/modals/EditCustomerModal.tsx
- frontend/src/components/modals/EditTeamMemberModal.tsx
- frontend/src/components/modals/RemovePeopleModal.tsx
- frontend/src/components/modals/TaskInfoModal.tsx
- frontend/src/components/modals/TaskRatingsInfoModal.tsx
- frontend/src/pages/MilestonesEditor.tsx
- frontend/src/redux/roadmaps/actions.ts
- frontend/src/redux/roadmaps/index.ts
- frontend/src/redux/roadmaps/reducers.ts
- frontend/src/redux/roadmaps/selectors.ts
- frontend/src/redux/roadmaps/types.ts
- frontend/src/routers/RoadmapRouter.tsx
- AllUsers are renamed to users and they are added under the corresponding roadmap.
- Roadmap users can be selected by the id of a roadmap in addition to the selected/current roadmap id
- Users from other roadmaps can now be fetched
> Modify frontend users

- frontend/src/components/TaskHeatmap.tsx
Also use hls, as it is nicer to work with.
The specific hsl ranges could be tweaked, if there is some actual design for this at some point.
Now hue range follows relatively closely the previous one.
Couple examples with ~200 tasks, first with random ratings, second with more concentrated (still random) ratings:
> Use relative value in heatmap

- frontend/src/components/RoadmapOverview.tsx
- frontend/src/components/TableUnratedTaskRow.tsx
- frontend/src/components/TaskTable.tsx
- frontend/src/components/TaskValueCreatedVisualization.tsx
- frontend/src/components/UserInfoCard.tsx
- frontend/src/components/modals/AddCustomerModal.tsx
- frontend/src/components/modals/EditCustomerModal.tsx
- frontend/src/components/modals/RateTaskModal.tsx
- frontend/src/pages/DashboardPage.tsx
- frontend/src/pages/MilestonesEditor.tsx
- frontend/src/pages/RegisterPage.tsx
- frontend/src/pages/TimeEstimationPage.tsx
- frontend/src/redux/roadmaps/reducers.ts
- frontend/src/redux/roadmaps/types.ts
- frontend/src/redux/versions/actions.ts
- frontend/src/utils/TaskUtils.ts
Corrected `Roadmap.customers`'s type to include `undefined`
Also removed some unnecessary uses of `?.` and `!.`
> Type correction

- frontend/src/components/CustomerStakesVisualization.module.scss
- frontend/src/components/CustomerStakesVisualization.tsx
- frontend/src/components/TaskValueCreatedVisualization.module.scss
- frontend/src/components/TaskValueCreatedVisualization.tsx
- frontend/src/redux/roadmaps/types.ts
- The customer stakes visualization is refactored to its own component
It can be utilized to visualize an individual milestones' (or task's) customer stakes.
> Refactor customer stakes visualization

- frontend/src/components/modals/AddTaskModal.tsx
- frontend/src/utils/UserUtils.ts
- Skip task rating if there are no customers to rate for.
Looks like the task rating draft pr is going to take time to complete. I separated the task creation modal bugfix to this pr.
> Fix task creation modal

- frontend/src/components/InfoTooltip.tsx
I feel that hovering over the tooltip is more intuitive than clicking on the icon in order for it to stay open. 
- Added interactive prop to tooltip; The tooltip will not close when user hovers over it. The delay to close the tooltip is 500ms.
> Add tooltip improvements

- frontend/src/components/modals/EditVersionModal.module.scss
- frontend/src/components/modals/EditVersionModal.tsx
- frontend/src/routers/MainRouter.tsx
- frontend/src/routers/RoadmapRouter.tsx
Since roadmap overview was moved higher level router, roadmap deletion modal did not open. Moved modal opening to MainRouter.
Fixed EditVersionModal's styles.
> Fix modals

- frontend/src/components/CustomerStakesVisualization.tsx
- frontend/src/components/TaskValueCreatedVisualization.module.scss
- Small visual fix: removed the first grey dot
> Fix no ratings CustomerStakesVisualization

- frontend/src/components/LoginNavBar.tsx
- frontend/src/pages/RegisterPage.tsx
- redirectTo context used to get lost when moving to register page
- now the joining link can be used with registering
> Retain search context between login/register pages

- server/src/utils/sendEmail.ts
Otherwise the sent email is only logged to the console.
This should allow easier experimenting on the development environment.
Set `NODE_ENV=production` to use the real service.
> Use real ses client only on production environment

- frontend/src/components/ControlledTooltip.tsx
- frontend/src/components/forms/StepForm.module.scss
- frontend/src/components/forms/StepForm.tsx
- frontend/src/components/modals/AddCustomerModal.module.scss
- frontend/src/components/modals/AddCustomerModal.tsx
- frontend/src/components/modals/AddRoadmapModal.module.scss
- frontend/src/components/modals/AddRoadmapModal.tsx
- frontend/src/components/modals/AddTeamMemberModal.module.scss
- frontend/src/components/modals/modalparts/SummaryStepContent.module.scss
- frontend/src/components/modals/modalparts/SummaryStepContent.tsx
- frontend/src/components/modals/modalparts/TeamMemberModalParts.module.scss
- frontend/src/components/modals/modalparts/TeamMemberModalParts.tsx
- frontend/src/i18/english.ts
- frontend/src/redux/roadmaps/types.ts
- frontend/src/shared.scss
Details
- The 'add member' button is displayed at the top while no members are present. Otherwise, it's displayed at the bottom
- The member list is scrollable, with a static add button
- a warning tooltip is shown when 'skip it' is clicked with added members present
- If any members were added, a link to people page is included in the last part:
> Add member invititation step to roadmap creation

- frontend/src/api/api.tsx
- frontend/src/components/RoadmapSelectorWidget.tsx
- frontend/src/components/UserInfoCard.tsx
- frontend/src/pages/ConfigurationPage.tsx
- frontend/src/pages/CreateProjectPage.tsx
- frontend/src/pages/JoinRoadmapPage.tsx
- frontend/src/pages/ProjectOverviewPage.tsx
- frontend/src/pages/UserInfoPage.tsx
- frontend/src/pages/VerifyEmailPage.tsx
- frontend/src/redux/user/actions.ts
- frontend/src/redux/user/index.ts
- frontend/src/redux/user/reducers.ts
- frontend/src/redux/user/types.ts
- frontend/src/routers/MainRouter.tsx
- frontend/src/routers/RoadmapRouter.tsx
- frontend/src/routers/paths.ts
- frontend/src/utils/requirelogin.tsx
- server/src/api/emailVerification/emailVerification.controller.ts
- server/src/api/emailVerification/emailVerification.model.ts
- server/src/api/roadmaps/roadmaps.routes.ts
- server/src/api/users/users.controller.ts
- server/src/api/users/users.model.ts
- server/src/api/users/users.routes.ts
- server/src/migrations/20210908133847_emailVerification.ts
- server/src/seeds/testdata.ts
- server/src/utils/forbidden.ts
- server/src/utils/requireAuth.ts
- server/tests/users.test.ts
Verification link is automatically sent when:
- new user is registered
- user's email is updated
Verified email is now required for all pages requiring login, except:
- user info page, this page is very WIP, but it now shows the
verification status, it has a button to send a new verification link,
and changing the user's email would also be done here
- verify email page, obviously
Verified email is now also required on the server side.
> Email verification

- frontend/src/components/TaskRatingsText.module.scss
- frontend/src/components/TaskRatingsText.tsx
- frontend/src/pages/TaskMapPage.module.scss
- frontend/src/pages/TaskMapPage.tsx
Small style changes to task-map
> Improve task-map styles

- frontend/src/components/TaskMapConnection.module.scss
- frontend/src/components/TaskMapConnection.tsx
- frontend/src/components/TaskMapEdge.module.scss
- frontend/src/components/TaskMapEdge.tsx
- frontend/src/components/TaskRatingsText.module.scss
- frontend/src/components/TaskRatingsText.tsx
- frontend/src/pages/TaskMapPage.module.scss
- frontend/src/pages/TaskMapPage.tsx
- frontend/src/shared.scss
- Added new files for edges and connection lines to components folder
- Fixed bug where edges would be behind task-components
- Added custom styling for edges and connectionlines (gradient works now)
- Fixed bug where edges would be invisible if they were straight lines (sourceY and targetY same value)
- Edges have hover effect
> Improve react-flow styling

- frontend/src/components/TableCustomerRow.tsx
- frontend/src/components/TaskTableRated.tsx
- frontend/src/components/TaskTableUnrated.tsx
- frontend/src/routers/paths.ts
Fixed the same bug in rated tasks and customers also, so those should be safe to use on other pages now.
> Fix dashboard task links

- frontend/src/components/TaskTable.module.scss
- frontend/src/components/TaskTableRated.tsx
- frontend/src/components/TaskTableUnrated.tsx
- frontend/src/components/modals/ModalRoot.tsx
- frontend/src/components/modals/RemoveTaskModal.tsx
- frontend/src/components/modals/types.ts
- frontend/src/i18/english.ts
Added similar deletion functionality for tasks as there are in clients. You can now delete tasks by clicking the trashcan icon in the task tables.
> Add functionality for removing tasks through tasklist

- frontend/src/components/CustomerListTable.tsx
- frontend/src/components/RoadmapOverview.tsx
- frontend/src/components/SortableTask.tsx
- frontend/src/components/TableCustomerRow.tsx
- frontend/src/components/TaskTableRated.tsx
- frontend/src/components/TaskTableUnrated.tsx
- frontend/src/components/TeamMemberListTable.tsx
- frontend/src/components/modals/AddCustomerModal.tsx
- frontend/src/components/modals/EditCustomerModal.tsx
- frontend/src/components/modals/NotifyUsersModal.tsx
- frontend/src/components/modals/TaskInfoModal.tsx
- frontend/src/components/modals/TaskRatingsInfoModal.tsx
- frontend/src/pages/ClientOverviewPage.tsx
- frontend/src/pages/MilestonesEditor.tsx
- frontend/src/pages/PlannerWeightsPage.tsx
- frontend/src/pages/RoadmapGraphPage.tsx
- frontend/src/pages/TaskListPage.tsx
- frontend/src/pages/TaskOverviewPage.tsx
- frontend/src/pages/TeamListPage.tsx
- frontend/src/pages/TimeEstimationPage.tsx
- frontend/src/redux/roadmaps/actions.ts
- frontend/src/redux/roadmaps/selectors.ts
- frontend/src/redux/roadmaps/types.ts
- frontend/src/routers/RoadmapRouter.tsx
- frontend/src/utils/TaskUtils.ts
Used the role selector in `TableCustomerRow` and `TaskTableRated`, other places needed user info for not only the role.
> Use role selector

- frontend/package.json
- frontend/src/redux/index.ts
- frontend/yarn.lock
https://trello.com/c/zdkcdyKu/385-redux-staten-synkronointi-v%C3%A4lilehtien-v%C3%A4lill%C3%A4-redux-persist
- Initialize new tabs with existing redux state from other tabs
- Sync redux state across tabs in realtime
I also fiddled with redux persist in redux-sync-persist -branch. It allows saving the state to localstorage. However, persist does not fit in with the current implementation since UserState defines if the user is logged in.
> Add redux state sync

- frontend/src/components/ProjectSummary.module.scss
- frontend/src/components/ProjectSummary.tsx
The "delete roadmap" option is now only shown to users with required permissions (e.i. admin users)
Also noticed the text alignment on the items was inconsistent between link elements (start), and button elements (center). Changed button text to be start aligned.
> Check permission

- frontend/src/components/TaskMapTask.module.scss
- frontend/src/components/TaskMapTask.tsx
- frontend/src/components/TaskMapTaskGroup.module.scss
https://trello.com/c/z9xskpGu/389-fiksaa-tyylit-mukautumaan-pitkiin-nimiin
> Add stretching for long names in taskmap

- frontend/src/components/Overview.module.scss
- frontend/src/components/Overview.tsx
https://trello.com/c/97muxs4h/410-eteenp%C3%A4in-taaksep%C3%A4in-napit-el%C3%A4%C3%A4-kun-kelaa-taskista-toiseen-riippuen-taskin-nimen-pituudesta
> Fix overview browse buttons

- frontend/src/components/Dot.tsx
- frontend/src/components/modals/modalparts/ColorPicker.module.scss
- frontend/src/components/modals/modalparts/ColorPicker.tsx
The colour is shown as a dot next to the hex input field.
> Show selected colour in customer edit modal

- frontend/src/components/CustomerListTable.tsx
- frontend/src/components/InvitationListTable.tsx
- frontend/src/components/Table.tsx
- frontend/src/components/TaskTable.module.scss
- frontend/src/components/TaskTableRated.tsx
- frontend/src/components/TaskTableUnrated.tsx
Given the minimum widths, the buttons will not clip.
The table will scroll sideways when it doesn't fit into the view.
The minimum width is defined as pixels / fr unit. The column widths are
always defined in fr units.
> Add minimum width to table component

- frontend/src/components/modals/JoinProjectModal.tsx
- frontend/src/components/modals/modalparts/TeamMemberModalParts.tsx
- frontend/src/i18/english.ts
https://trello.com/c/xbtRuXDg/418-muuta-teksteihin-business-rooli-sales-representative
> Use role translations

- server/src/api/invitations/invitations.controller.ts
The cleanup is implemented as middleware in post invitations -route
> Add old invitation cleanup

- frontend/src/components/LoginNavBar.tsx
- frontend/src/components/NavBar.tsx
- frontend/src/i18/english.ts
- frontend/src/pages/NotFoundPage.module.scss
- frontend/src/pages/NotFoundPage.tsx
Update the page according to the latest figma design
> Update 404 -page

- frontend/src/api/api.tsx
- frontend/src/components/TaskTableUnrated.tsx
- frontend/src/components/modals/AddTaskModal.tsx
- frontend/src/components/modals/RateTaskModal.tsx
- frontend/src/components/modals/types.ts
- frontend/src/i18/english.ts
- frontend/src/redux/roadmaps/actions.ts
- frontend/src/redux/roadmaps/index.ts
- frontend/src/redux/roadmaps/reducers.ts
- frontend/src/utils/TaskUtils.ts
- server/src/api/taskratings/taskratings.controller.ts
- server/src/api/taskratings/taskratings.routes.ts
- server/tests/taskratings.test.ts
Routes for adding/patching multiple ratings with one request. Either all or no ratings get added/patched.
In task rating modal user can only either patch or add ratings. (all changes need to be done in one request and it would not be good practice to make post and patch queries in the same route)
> Multiple task ratings

- frontend/src/utils/TaskUtils.ts
Small refactor & comments added as well
> Fix awaitsUserRatings for users with no customers represented

- frontend/src/components/TaskTableRated.tsx
- frontend/src/components/TaskTableUnrated.tsx
- frontend/src/components/modals/InfoModal.module.scss
- frontend/src/components/modals/InfoModal.tsx
- frontend/src/components/modals/ModalRoot.tsx
- frontend/src/components/modals/types.ts
- frontend/src/i18/english.ts
- frontend/src/pages/ConfigurationPage.module.scss
- frontend/src/pages/ConfigurationPage.tsx
- frontend/src/pages/MilestonesEditor.module.scss
- frontend/src/pages/MilestonesEditor.tsx
- frontend/src/pages/PlannerWeightsPage.tsx
- frontend/src/pages/RoadmapGraphPage.tsx
- frontend/src/pages/TimeEstimationPage.module.scss
- frontend/src/pages/TimeEstimationPage.tsx
- frontend/src/redux/roadmaps/types.ts
- frontend/src/shared.scss
Added missing tooltips. The ones in the settings didn't have specified texts yet so I left them to TBD for now.
> Info texts

- frontend/src/pages/TaskMapPage.tsx
Fits the map to the view on first load.
Also simplified the position tracking a bit.
> Center task map on open

- frontend/src/components/RatingTable.module.scss
- frontend/src/components/RatingTable.tsx
- frontend/src/components/RatingTableValue.tsx
- frontend/src/components/RatingTableWork.tsx
- frontend/src/pages/TaskOverviewPage.tsx
- server/src/api/roadmaps/roadmaps.controller.ts
- server/src/api/users/users.model.ts
- shared/types/customTypes.ts
Added RoadmapReadUsers permission to Business-role
- Business-users can read either Developer-users or users with at least one same represented customer
- This enables business-users to see who rated listed ratings. It could have been confusing otherwise, as the user could not even identify their own ratings in the list
> Edit task ratings

- server/src/api/passwordReset/passwordReset.model.ts
- server/src/api/users/users.controller.ts
- server/src/api/users/users.routes.ts
- server/src/migrations/20220117144935_passwordReset.ts
Routes:
- POST /users/sendPasswordResetLink
- POST /users/resetPassword
> Add password reset backend

- frontend/src/pages/ProjectOverviewPage.tsx
Sort by alphabetical order of roadmap names
> Sort roadmaps in ProjectOverviewPage

- frontend/src/pages/RoadmapGraphPage.tsx
- frontend/src/redux/roadmaps/actions.ts
It was missing dispatch for the versions data
> Fix planner graph page reload

- frontend/src/components/TaskMapTask.module.scss
- frontend/src/components/TaskMapTask.tsx
- frontend/src/components/TaskMapTaskGroup.module.scss
- frontend/src/components/TaskMapTaskGroup.tsx
- frontend/src/pages/TaskMapPage.tsx
- frontend/src/utils/TaskRelationUtils.ts
- server/src/api/taskrelation/taskrelation.controller.ts
- server/src/utils/typeValidation.ts
While drawing a new connection:
- tasks that can not be connected to are grayed out
- handles that can accept the connection are highlighted
While dragging task from synergy group to another, unavailable groups are grayed out.
On the server side, the graph is validated each time new relations are added.
Deleting relations will never invalidate the graph.
> Task map validation

- START_LINUX.sh
- START_WINDOWS.bat
- frontend/src/components/MilestoneRatingsSummary.tsx
- frontend/src/components/PlannerChart.tsx
- frontend/src/components/RatingBars.tsx
- frontend/src/components/RatingTable.tsx
- frontend/src/components/RatingTableComplexity.tsx
- frontend/src/components/RoadmapOverview.tsx
- frontend/src/components/TaskHeatmap.module.scss
- frontend/src/components/TaskHeatmap.tsx
- frontend/src/components/TaskRatingsText.tsx
- frontend/src/components/TaskTableRated.tsx
- frontend/src/components/TaskTableUnrated.tsx
- frontend/src/components/TaskValueCreatedVisualization.tsx
- frontend/src/components/modals/RateTaskModal.tsx
- frontend/src/i18/english.ts
- frontend/src/pages/LandingPage.tsx
- frontend/src/pages/RoadmapGraphPage.tsx
- frontend/src/pages/TaskOverviewPage.tsx
- frontend/src/pages/TimeEstimationPage.tsx
- frontend/src/utils/TaskUtils.ts
- server/src/api/taskratings/taskratings.controller.ts
- server/src/api/taskratings/taskratings.model.ts
- server/src/seeds/testdata.ts
- server/tests/taskratings.test.ts
- shared/types/customTypes.ts
"Work" term is now only used in connection to time estimation (workdays being the time unit), otherwise tasks are rated etc. on "complexity"
> Rewording work -> complexity

- frontend/src/components/NavBar.module.scss
- frontend/src/components/NavBar.tsx
- frontend/src/components/RepresentativeTable.module.scss
- frontend/src/components/RepresentativeTable.tsx
- frontend/src/components/RoleIcons.module.scss
- frontend/src/components/RoleIcons.tsx
- frontend/src/components/TableInvitationRow.module.scss
- frontend/src/components/TableInvitationRow.tsx
- frontend/src/components/TableTeamMemberRow.module.scss
- frontend/src/components/TableTeamMemberRow.tsx
- frontend/src/components/UserInfoCard.module.scss
- frontend/src/components/UserInfoCard.tsx
- frontend/src/components/modals/AddCustomerModal.module.scss
- frontend/src/components/modals/AddCustomerModal.tsx
- frontend/src/components/modals/EditTeamMemberModal.module.scss
- frontend/src/components/modals/EditTeamMemberModal.tsx
- frontend/src/components/modals/NotifyUsersModal.module.scss
- frontend/src/components/modals/NotifyUsersModal.tsx
- frontend/src/components/modals/modalparts/CustomerModalParts.module.scss
- frontend/src/components/modals/modalparts/CustomerModalParts.tsx
- frontend/src/components/modals/modalparts/TeamMemberModalParts.module.scss
- frontend/src/components/modals/modalparts/TeamMemberModalParts.tsx
The component displays an icon corresponding to the RoleType.
- Tooltip versions of the RoleIcon's are added to places where the role name cannot be deduced from nearby elements.
- The tooltips are a bit out of align in lists made with the table-component, such as representatives and invitations lists. Does it look bad a.k.a should I spend time fixing this?
> Roletype icon component

- frontend/src/components/TaskModalButtons.module.scss
- frontend/src/components/TaskModalButtons.tsx
- frontend/src/components/modals/NotifyUsersModal.tsx
- frontend/src/components/modals/types.ts
- frontend/src/redux/roadmaps/types.ts
Notify users button would still be visible even if the notification modal had no users. This fix hides the button if there are no users to notify
> Empty notification modal fix

- server/src/api/roadmaps/roadmaps.controller.ts
https://trello.com/c/9HV3MIpd/529-representative-pit%C3%A4%C3%A4-poistaa-asiakkaalta-kun-kyseinen-k%C3%A4ytt%C3%A4j%C3%A4-poistuu-roadmapista
> Delete representativeships when leaving a roadmap

- frontend/src/pages/RoadmapGraphPage.tsx
- frontend/src/utils/TaskUtils.ts
Customer dots size calculation included version's weighted totalValue.
Calculate also unweighted values and totalValues in totalValuesAndComplexity-function.
Unweighted totalValues are now used in customer visualization.
> Fix customer visualization values

- frontend/.eslintrc.js
- frontend/package.json
- frontend/src/components/Overview.tsx
- frontend/src/components/SocketListener.tsx
- frontend/src/components/modals/AddCustomerModal.tsx
- frontend/src/components/modals/AddRoadmapModal.tsx
- frontend/src/components/modals/AddTaskModal.tsx
- frontend/src/components/modals/AddTeamMemberModal.tsx
- frontend/src/components/modals/AddVersionModal.tsx
- frontend/src/components/modals/DeleteModal.tsx
- frontend/src/components/modals/EditTeamMemberModal.tsx
- frontend/src/components/modals/EditVersionModal.tsx
- frontend/src/components/modals/ImportTasksModal.tsx
- frontend/src/components/modals/IntegrationConfigurationModal.tsx
- frontend/src/components/modals/IntegrationOauthModal.tsx
- frontend/src/components/modals/RateTaskModal.tsx
- frontend/src/components/modals/RemovePeopleModal.tsx
- frontend/src/components/modals/RemoveTaskModal.tsx
- frontend/src/components/modals/SendInvitationModal.tsx
- frontend/src/pages/TaskOverviewPage.tsx
- frontend/src/routers/MainRouter.tsx
- frontend/src/utils/SortUtils.ts
- frontend/yarn.lock
- server/package.json
- server/src/api/taskrelation/taskrelation.controller.ts
- server/src/server.ts
- server/src/utils/errorhandler.ts
- server/yarn.lock
This should be merged with #311 once the other upgrades are merged
> Upgrade typescript

- frontend/src/components/ExpandableColumn.module.scss
Change color of expand more and expand less icons to $COLOR-FOREST while hovering over them
> Add color-forest hover effect to expand icons

- frontend/src/pages/TimeEstimationPage.module.scss
class horizontalLine has width:auto, fixed the issue of too long horizontal lines on Planner time estimation task boxes
> class horizontalLine has width:auto, fixed the issue of too long horizontal lines on Planner time estimation task boxes

- frontend/src/shared.scss
https://trello.com/c/Ieoydwug/554-modaalien-ja-topbar-elementtien-z-j%C3%A4rjestys
> Fix react modal's z-index

- frontend/src/components/TaskRelationTable.tsx
- frontend/src/components/modals/ImportTasksModal.tsx
- frontend/src/i18/english.ts
- frontend/src/pages/TaskOverviewPage.module.scss
- frontend/src/pages/TaskOverviewPage.tsx
- frontend/src/shared.scss
- server/src/api/taskrelation/taskrelation.controller.ts
~~The react-select styles are not quite there yet~~
This still has the same placeholder text for each type
> Edit relations from task overview

- frontend/src/components/TaskMapTask.module.scss
- frontend/src/components/TaskMapTask.tsx
Now the whole task is disabled (style-wise) instead of only the handle.
> Add disable-effect for unconnectable tasks

- frontend/src/components/TaskRelationTable.tsx
- frontend/src/components/modals/ImportTasksModal.tsx
Select's menu appeared behind the modal
> Fix modal's select-component z-index

- frontend/src/components/ExpandableColumn.module.scss
- frontend/src/pages/MilestonesEditor.module.scss
- frontend/src/pages/MilestonesEditor.tsx
ExpandableColumn renders untoggled if there are no unordered tasks.
> Close ExpandableColumn on render if empty

- frontend/src/redux/roadmaps/types.ts
- server/src/api/tasks/tasks.controller.ts
- server/src/api/tasks/tasks.model.ts
- server/src/migrations/20220328082207_taskEditTimestamp.ts
Backend support for saving tasks' last modified timestamps and userId who did the edit
> Add updatedAt & lastEditedBy to task model & schema

- frontend/src/components/Overview.module.scss
- frontend/src/components/Overview.tsx
- frontend/src/i18/english.ts
- frontend/src/pages/TaskMapPage.tsx
- frontend/src/pages/TaskOverviewPage.tsx
- shared/utils/date.ts
**When task has been modified:**
**When task has not been modified:**
> Add tasks' "last modified" field into overview component

- frontend/src/components/BlockGraph.tsx
- frontend/src/components/CustomerStakesVisualization.tsx
- frontend/src/components/MetricsSummary.module.scss
- frontend/src/components/MetricsSummary.tsx
- frontend/src/components/RoadmapGraphSidebar.module.scss
- frontend/src/components/RoadmapGraphSidebar.tsx
- frontend/src/components/RoadmapSelectorWidget.module.scss
- frontend/src/components/TaskRelationTable.module.scss
- frontend/src/components/TaskRelationTable.tsx
- frontend/src/components/TaskTable.module.scss
- frontend/src/components/TaskTable.tsx
- frontend/src/components/TaskValueCreatedVisualization.module.scss
- frontend/src/components/TaskValueCreatedVisualization.tsx
- frontend/src/pages/RoadmapGraphPage.module.scss
- frontend/src/pages/RoadmapGraphPage.tsx
- frontend/src/redux/roadmaps/types.ts
- frontend/src/shared.scss
Sidebar is shown, when a milestone is selected
- Selection is cleared if plannerPagecontainer-div or the close-button is clicked
- Sidebar pushes other content to the left, so no milestones are hidden behind it
- MUI drawer component is used due to convenience
- A few components are modified to fit the design of the sidebar
> Add milestone sidebar to RoadmapGraphPage

- frontend/src/pages/ClientOverviewPage.tsx
- frontend/src/pages/TaskMapPage.tsx
Noticed a failing query on task map page for `/roadmaps/NaN/users`
> Query fixes

- frontend/src/api/api.ts
The versions are also dependent on the tasks.
> Fix versions invalidation

- frontend/src/components/forms/Checkbox.tsx
- frontend/src/pages/RegisterPage.tsx
Small refactor to use the Checkbox-component in RegisterPage to avoid code duplication.
> Change Checkbox-component label to optional

- frontend/src/components/BlockGraph.module.scss
- frontend/src/components/RoadmapGraphSidebar.module.scss
- frontend/src/components/RoadmapGraphSidebar.tsx
- frontend/src/i18/english.ts
- frontend/src/pages/MilestonesEditor.module.scss
- frontend/src/pages/MilestonesEditor.tsx
- frontend/src/pages/RoadmapGraphPage.module.scss
- frontend/src/pages/RoadmapGraphPage.tsx
CTRL + click supports multiselection.
Unify selection styles in RoadmapGraph and MilestonesEditor.
- Should the selection be cleared when milestones or tasks are dragged?
> Add milestone selection to MilestonesEditor

- server/src/api/trello/trelloIntegration.ts
https://developer.atlassian.com/cloud/trello/guides/rest-api/authorization/#1-authorize--route-options
> Remove expiration from trello authorisation

- frontend/src/components/MetricsSummary.tsx
- frontend/src/pages/PlannerWeightsPage.module.scss
- frontend/src/pages/PlannerWeightsPage.tsx
Since we have the visualization component ready, added it to client weights -page
> Use shares visualization in client weights -page

- frontend/src/colors.module.scss
- frontend/src/components/BlockGraph.module.scss
- frontend/src/pages/MilestonesEditor.module.scss
- frontend/src/pages/MilestonesEditor.tsx
Includes 
https://trello.com/c/1WTsgE5r/634-unselect-milestones-kun-jotain-raahataan
https://trello.com/c/ibh3FxTt/635-valitun-completed-milestonen-taustav%C3%A4ri
Keep milestone selection when clicking the 'add new milestone'-button
> Milestone selection fixes

- frontend/src/components/CustomerStakesScore.module.scss
- frontend/src/components/CustomerStakesScore.tsx
- frontend/src/components/TaskValueCreatedVisualization.module.scss
- frontend/src/components/TaskValueCreatedVisualization.tsx
- frontend/src/i18/english.ts
- frontend/src/pages/MilestonesEditor.module.scss
- frontend/src/pages/MilestonesEditor.tsx
- frontend/src/redux/roadmaps/types.ts
- frontend/src/utils/CustomerUtils.ts
Calculate the difference between the actual and target shares. If the result is more than a 30% decrease, it is considered as a poor score.
> Add milestone shares scores to MilestonesEditor

- frontend/src/components/MilestoneCompletedness.module.scss
- frontend/src/components/MilestoneCompletedness.tsx
- frontend/src/components/PercentageBar.tsx
- frontend/src/pages/MilestonesEditor.tsx
Completedness-visualization is used in planner/milestones (https://trello.com/c/uTPOBO3w/468-plan-milestones-valmiusaste)
> Add milestone completedness visualization

- frontend/src/components/SortableTask.tsx
- frontend/src/components/TaskTable.module.scss
- frontend/src/components/TaskTable.tsx
- frontend/src/components/modals/ModalRoot.tsx
- frontend/src/components/modals/RelationsModal.module.scss
- frontend/src/components/modals/RelationsModal.tsx
- frontend/src/components/modals/modalparts/Info.module.scss
- frontend/src/components/modals/modalparts/Info.tsx
- frontend/src/components/modals/modalparts/TeamMemberModalParts.module.scss
- frontend/src/components/modals/modalparts/TeamMemberModalParts.tsx
- frontend/src/components/modals/types.ts
- frontend/src/i18/english.ts
Works and looks decent, but:
- ~~this does not implement the option to show the milestone names yet~~
- the modal is by uncomfortably large part, copy pasted from task relation table
- missing translations
> Planner relation modal

- frontend/src/pages/MilestonesEditor.tsx
https://trello.com/c/7OrpzLOv/658-plan-milestones-jos-client-weightej%C3%A4-ei-voi-lukea-client-shares-scorea-ei-tarvitse-n%C3%A4ytt%C3%A4%C3%A4
RoadmapReadCustomerValues -permission is required to view shares visualization and milestone shares score
> Require permission for client value visualizations

- frontend/src/components/TaskMap.module.scss
- frontend/src/components/TaskMap.tsx
- frontend/src/components/TaskMapTask.module.scss
- frontend/src/components/TaskMapTask.tsx
- frontend/src/components/TaskRatingsText.module.scss
- frontend/src/components/TaskRatingsText.tsx
https://trello.com/c/ojE7isyv/660-taskien-arvot-pois-task-map-listauksesta
Also all tasks are changed to same height, removing the need for calculating task name heights.
> Remove task map task ratings

- frontend/src/pages/PlannerWeightsPage.tsx
- server/src/migrations/20220513081959_addPermissionRoadmapReadCustomerValuesToBusinessRole.ts
- shared/types/customTypes.ts
https://trello.com/c/s114XVIP/662-plan-business-k%C3%A4ytt%C3%A4j%C3%A4t-saavat-lukea-asiakkaiden-weightit
> Client values read-permission for business role

- frontend/src/api/api.ts
- frontend/src/components/EditableSelect.module.scss
- frontend/src/components/EditableSelect.tsx
- frontend/src/components/Overview.module.scss
- frontend/src/components/Overview.tsx
- frontend/src/components/forms/FormField.tsx
- frontend/src/pages/ClientOverviewPage.tsx
- frontend/src/pages/TaskMapPage.tsx
- frontend/src/pages/TaskOverviewPage.tsx
As a note, I gave up (at least for now) creating the generic/reusable withButtons due to time constraints for the UX test session. EditableSelect and -field were too different.
> Task status edition

- frontend/src/routers/PlannerPageRouter.tsx
https://trello.com/c/HxJQCRbe/686-plan-tab-j%C3%A4rjestyksen-muuttaminen
> Reorder milestones as the 1st tab of planner page

- frontend/src/components/RatingTable.module.scss
- frontend/src/components/RatingTable.tsx
Render newlines and set max height higher
> Small rating table fixes

- frontend/src/components/RoadmapSidebar.tsx
- frontend/src/routers/RoadmapRouter.tsx
- frontend/src/routers/paths.ts
Change route from "/configure" to "/settings"
> Fix settings route

- frontend/src/components/TaskMapEdge.module.scss
- frontend/src/components/TaskMapEdge.tsx
Right or left clicking edges on task map now opens context menu where you can delete the relation.
> Add context menu for removing taskmap edges

- frontend/src/components/TaskMap.module.scss
- frontend/src/components/TaskMap.tsx
- frontend/src/i18/english.ts
Moved the task map controls from bottom left to top right corner. Also made the icons a bit larger, any opinions on that? Are they good now or should they be changed more (to either smaller or bigger)
> Move taskmap controls to top corner

- frontend/src/components/RoadmapCompletionMeter.tsx
- frontend/src/components/TaskHeatmap.tsx
- frontend/src/components/TaskMapTask.tsx
- frontend/src/components/TaskTable.tsx
- frontend/src/components/TaskTableRated.tsx
- frontend/src/utils/TaskUtils.ts
https://trello.com/c/FuntYSh9/624-dashboard-valmiit-taskit-pois-heatmapista
> Hide completed tasks from TaskHeatmap

- frontend/src/pages/ClientOverviewPage.module.scss
- frontend/src/pages/ClientOverviewPage.tsx
Small fix: https://trello.com/c/UZEssfWr/701-clientoverview-pallon-ja-nimen-v%C3%A4lille-lis%C3%A4%C3%A4-v%C3%A4li%C3%A4
> Add a gap to client name and dot in client details

- frontend/src/components/Overview.module.scss
- frontend/src/components/Overview.tsx
- frontend/src/pages/ConfigurationPage.tsx
Use vertical styling in settings-page project overview
> Add vertical Overview styles

- frontend/src/api/api.ts
- frontend/src/components/ControlledTooltip.tsx
- frontend/src/components/InfoTooltip.tsx
- frontend/src/components/NavBar.module.scss
- frontend/src/components/modals/AddRoadmapModal.tsx
- frontend/src/components/modals/EditCustomerModal.tsx
- frontend/src/components/modals/modalparts/CustomerModalParts.tsx
- frontend/src/components/modals/modalparts/TeamMemberModalParts.tsx
- frontend/src/utils/TaskUtils.ts
- server/src/api/jira/jiraIntegration.ts
Couple things I've come across recently. Each commit is hopefully self explanatory enough.
> Refactoring

- frontend/src/shared.scss
Minor fix, classes not in use but fixed for possible future usage
> Fix overflow-y -> overflow-x in shared classes overflowX*

- frontend/src/pages/ProjectOverviewPage.module.scss
- frontend/src/pages/TaskListPage.module.scss
- frontend/src/pages/TaskListPage.tsx
https://trello.com/c/S5O0WEsp/705-marginia-scollbareihin
I would have added space with margins, but they seemed to have no effect on the scrollbar. So implemented this with borders instead.
> Add margin between multiple scrollbars

- frontend/src/components/RoadmapSelectorWidget.tsx
- frontend/src/components/TableCustomerRow.module.scss
- frontend/src/components/TableCustomerRow.tsx
- frontend/src/components/UserInfoCard.module.scss
- frontend/src/components/forms/DropdownGreen.module.scss
- frontend/src/i18/english.ts
- frontend/src/pages/CreateProjectPage.module.scss
- frontend/src/pages/CreateProjectPage.tsx
- frontend/src/pages/VerifyEmailPage.module.scss
- frontend/src/pages/VerifyEmailPage.tsx
- frontend/src/shared.scss
https://trello.com/c/xrtft6nz/717-project-overview-get-started-ei-mahdu-kunnolla-roadmap-selector-widgettiin
https://trello.com/c/AQmgV5c6/718-getstarted-email-voi-overflowaa
https://trello.com/c/1RkRW7Io/715-user-alignaa-role-ikoni-keskelle-projects-listassa
> Style fixes

- frontend/src/components/modals/RelationsModal.module.scss
- frontend/src/components/modals/RelationsModal.tsx
Max. 3 lines of the task description are displayed
https://trello.com/c/Lzi2l18L/722-lis%C3%A4%C3%A4-task-relations-sivupaneeliin-tarkasteltavan-taskin-nimidetails
> Add task name and description to RelationsModal

- frontend/src/components/SortableTask.module.scss
- frontend/src/components/SortableTask.tsx
- frontend/src/components/SortableTaskList.tsx
- frontend/src/pages/MilestonesEditor.tsx
Adds milestone value-shares visualization to planner
The width of the PercentageBar is calculated as following: total task value / max. total task value. 
- to determine the max. total value, the number of **all** clients * max rating value is used
> Milestone value-shares visualization

- README.md
- frontend/src/i18/english.ts
Otherwise complete, but JIRA key locations / additional instructions are missing.
> Add integration instructions in README

- frontend/src/components/forms/Dropdown.tsx
- frontend/src/components/forms/DropdownGreenFilled.module.scss
- frontend/src/i18/english.ts
- frontend/src/pages/MilestonesEditor.module.scss
- frontend/src/pages/MilestonesEditor.tsx
Settings are saved to localStorage by setting string and current userId and roadmapId.
> Add view settings to milestones-editor
