Vincit/VISDOM-Roadmapper

- server/src/api/jiraconfigurations/jiraconfigurations.controller.ts
- server/src/api/jiraconfigurations/jiraconfigurations.model.ts
- server/src/api/roadmaps/roadmaps.controller.ts
- server/src/api/roles/roles.controller.ts
- server/src/api/taskratings/taskratings.controller.ts
- server/src/api/tasks/tasks.controller.ts
- server/src/api/users/users.controller.ts
- server/src/api/versions/versions.controller.ts
- Id's are now allowed, but discarded, in patch routes
- Id's are not used in post/patch queries
- patchCustomer is not modified, since Juho has already done that in customer-model-frontend -branch
> Delete id-fields before queries in POST/PATCH

- server/src/api/users/users.model.ts
- server/src/migrations/20210531133549_adjustColumnLengthConstraints.ts
The password field is ok, as it is stored hashed.
The hash uses bcrypt, which produces 60 character long hash.
One more consideration is the actual plain text password length. As
bcrypt only uses the first 72 bytes, the length might be good to limit
to more closely reflect the actual usable length.
> Change column lengths to match json schema

- frontend/src/redux/roadmaps/actions.ts
Typescript started complaining about these. It no longer automatically assumed that the caught errors are AxiosError<any> but they were instead typed as unknown
> Cast API axios errors to correct type

- frontend/src/components/TableTaskRow.tsx
- frontend/src/pages/DashboardPage.tsx
- frontend/src/utils/TaskUtils.ts
- server/src/seeds/testdata.ts
- server/tests/taskratings.test.ts
Rate-button was missing in tasks page's 'waiting for ratings'-list
and the task was not visible in dashboard, when one of represented
customers rating had already been given.
Business-users had rate-button if they had not rated yet - now it
shows the button if their ratings for represented customers are
missing.
Added a utility function for checking if ratings are needed.
> Fix task rating bug

- frontend/src/components/TableTaskRow.tsx
- frontend/src/utils/TaskUtils.ts
Business-user had a waiting for ratings -icon when it was not needed
(in practice, when they had not personally rated the task).
Business-user now has waiting for ratings -icons for customers they
represent and have not rated for yet.
> Fix waiting for ratings-icons

- frontend/src/components/TableTaskRow.module.scss
- frontend/src/components/TableTaskRow.tsx
- frontend/src/components/TaskValueCreatedVisualization.module.scss
- frontend/src/components/TaskValueCreatedVisualization.tsx
- frontend/src/pages/RoadmapGraphPage.module.scss
- frontend/src/pages/RoadmapGraphPage.tsx
- frontend/src/shared.scss
The commit message explains this feature in more detail.
Here's screenshots of some examples to get an idea of how it looks:
> Update customer stakes visualization

- frontend/src/components/TableUnratedTaskRow.tsx
Bug description: _If user who represents many customers at the same time gave rating to one of the customers, all customer dots in 'waiting for ratings' -column disappeared as if they had been rated already._
Waiting for ratings now takes "rating.forCustomer" into account as well instead of just "rating.createdByUser"
> Fix a task table customer-dot bug

- frontend/src/components/TaskValueCreatedVisualization.tsx
- frontend/src/i18/english.ts
- frontend/src/pages/PlannerWeightsPage.module.scss
- frontend/src/pages/PlannerWeightsPage.tsx
- frontend/src/utils/string.ts
- server/src/api/customer/customer.model.ts
- server/src/migrations/20210715135729_customerWeightToFloat.ts
Added a description to client weights page and adjusted the range of the slider to [0,2].
Modified database to use float type for customer weight.
Reset and save buttons are now disabled when no changes to customer weight have been made.
Slider labels are now not displayed with the exception of value 0. I'm not sure if I recall correctly how they were supposed to work and if the current implementation is good at all.
> Modify client weighting

- .gitignore
- server/src/api/taskratings/taskratings.controller.ts
- server/tests/taskratings.test.ts
Only fetch ratings belonging to the task.
Also added ignore for all `node_modules` and `.env` files
> Fix GET taskratings

- frontend/src/components/modals/RateTaskModal.tsx
- frontend/src/utils/TaskUtils.ts
Rate modal in task table would show customers from every roadmap if you represented them instead of showing the ones that belong to the chosen roadmap.
> Fix rating customers bug

- frontend/src/components/PlannerChart.tsx
- frontend/src/components/TaskTable.tsx
Dashboard would break because functions `calcTaskWeightedValueSum `and `unratedProductOwnerTasks `won't work when customers are empty. I added customer checks in the functions (works now) but I was wondering if this solution is the correct way? Or should the customer empty/undefined/null checks be in the components where you call these functions?
> Fix dashboard crash when there's no customers

- frontend/src/pages/RoadmapGraphPage.tsx
- frontend/src/utils/TaskUtils.ts
Multiply a client's ratings by their weight (or planner weight) before calculating the taskrating total value.
The scaled total value is displayed only in the roadmap graph versions. Should it be displayed in milestones editor too?
Height is calculated logarithmically: the full height of 350 is reached when a version's total value is a bit over 200.
`const h = Math.min(350, Math.max(100, 45 * Math.log2(ver.value)));`
> Add scaling to RoadmapGraphPage's total values

- frontend/src/components/PlannerChart.tsx
- frontend/src/components/TaskValueCreatedVisualization.tsx
- frontend/src/pages/MilestonesEditor.tsx
- frontend/src/pages/RoadmapGraphPage.tsx
- frontend/src/utils/TaskUtils.ts
- Scaled values are used in customer stakes calculations
Added extra parameter to taskUtils (notWeighted) in case the weighted/scaled values should not be used. (I recall discussion about using scaled values everywhere and adding a convenient on/off switch)
> Use scaled values in customer stakes

- frontend/src/components/NavBar.module.scss
- frontend/src/components/NavBar.tsx
- frontend/src/components/ProjectSummary.tsx
- frontend/src/components/RoadmapSelectorWidget.tsx
- frontend/src/components/RoadmapSidebar.tsx
- frontend/src/pages/ProjectOverviewPage.module.scss
- frontend/src/pages/ProjectOverviewPage.tsx
- frontend/src/redux/roadmaps/index.ts
- frontend/src/redux/roadmaps/reducers.ts
- frontend/src/routers/MainRouter.tsx
- frontend/src/routers/RoadmapRouter.tsx
- frontend/src/routers/paths.ts
- Changed route from 'roadmap/:selectedroadmapId/overview' to '/overview'.
- The sidebar will no longer show on the overview page.
- chosenRoadmap is removed from Localstorage when moving to the overview page, as no roadmap should be selected.
> Move project overview page to higher level router

- frontend/src/redux/roadmaps/actions.ts
Noticed that two actions were broken in milestone editor (add / remove task), because invalid hook call errors.
Didn't catch this when reviewing the pr few days back.
> Replace invalid uses of hooks

- frontend/src/api/api.tsx
- frontend/src/components/TableUnratedTaskRow.tsx
- frontend/src/components/modals/ModalRoot.tsx
- frontend/src/components/modals/NotifyUsersModal.module.scss
- frontend/src/components/modals/NotifyUsersModal.tsx
- frontend/src/components/modals/types.ts
- frontend/src/i18/english.ts
- frontend/src/redux/roadmaps/actions.ts
- frontend/src/redux/roadmaps/index.ts
- frontend/src/utils/TaskUtils.ts
Notifications modal for users that haven't given ratings when they should (it parses out logged in user, I figured that you don't want to send email to yourself). 
Currently it sends the api request to missing endpoint so it should give 404. 
Payload contains: List of users that were checked and the correct task.
> Add notification modal for missing ratings

- frontend/src/components/modals/RateTaskModal.tsx
Developers could not rate unrated tasks (rating modal was empty). Corrected filter predicate.
> Fix developer task rating

- frontend/src/components/TableUnratedTaskRow.tsx
Fixed bug: `Hide the task rating button(s) if user has no one to represent`
> Hide task rating buttons if user has no one to represent

- frontend/src/components/ProjectSummary.tsx
- frontend/src/pages/DashboardPage.tsx
- frontend/src/routers/RoadmapRouter.tsx
- frontend/src/utils/UserUtils.ts
Many api routes would give 403 forbidden errors, when user is not admin.
Now api calls are made only if user has the required permission.
> Adjust frontend to permission model

- frontend/src/components/CustomerListTable.tsx
- frontend/src/components/PlannerChart.tsx
- frontend/src/components/RoadmapCompletionMeter.tsx
- frontend/src/components/SortingArrow.tsx
- frontend/src/components/TableCustomerRow.tsx
- frontend/src/components/TableTeamMemberRow.tsx
- frontend/src/components/TaskTable.tsx
- frontend/src/components/TaskTableUnrated.tsx
- frontend/src/components/TeamMemberListTable.tsx
- frontend/src/components/modals/NotifyUsersModal.tsx
- frontend/src/pages/DashboardPage.tsx
- frontend/src/pages/MilestonesEditor.tsx
- frontend/src/pages/TaskListPage.tsx
- frontend/src/redux/roadmaps/actions.ts
- frontend/src/utils/SortCustomerUtils.ts
- frontend/src/utils/SortRoadmapUserUtils.ts
- frontend/src/utils/SortUtils.ts
- frontend/src/utils/TaskUtils.ts
- frontend/src/utils/array.ts
- started to rewrite / reorganise task utils into (hopefully) reusable predicates
- rewrote sorting to
- use decorate-sort-undecorate automatically for calculated keys
- allow object property key as sorting key
- use `undefined` as `NO_SORT`
- added `useSorting()` hook & SortingArrow component
> Task util refactor

- server/src/api/taskrelation/taskrelation.controller.ts
- server/src/api/taskrelation/taskrelation.model.ts
- server/src/api/taskrelation/taskrelation.routes.ts
- server/src/api/tasks/tasks.routes.ts
- server/src/migrations/20210823150208_taskRelations.ts
- shared/types/customTypes.ts
Endpoints: get, post, delete.
Patch doesn't really make so much sense for this.
The relations are returned as a list of directed edges, with the nodes `from` and `to`, and the `type` of the relation.
> Add task relations model

- frontend/package.json
- frontend/src/components/RatingBars.module.scss
- frontend/src/components/RatingBars.tsx
- frontend/src/components/TaskRatingWidget.module.scss
- frontend/src/components/TaskRatingWidget.tsx
- frontend/src/components/modals/RateTaskModal.tsx
- frontend/src/i18/english.ts
- frontend/yarn.lock
Task rating is skipped on task creation if there are no customers to rate for
"Fixed" task rating modal styles according to figma
- Well, the styles look correct, but functionality feels messed up. Material UI's rating component allows the user to unselect the rating. Not sure if I would have used the component if I knew the feature could not be disabled...
- <b>Example</b>: admin represents two customers -> they rate and submit the first customer's rating -> the rating modal can be opened again and the submitted rating can be unselected -> the submission will go through without error msgs, but the rating will not be patched
- Any ideas on the user flow? Should all ratings be given in one submission so the modal cannot be revisited? Or perhaps on submission, compare the initial and given …
> Task rating

- server/src/api/users/users.model.ts
- server/tests/roadmaps.test.ts
- server/tests/setuptests.ts
Refactored roadmap tests to be more accurate
Most relevant changes:
-Compare data on API to DB
-Create agentData variable to remove hardcoded data around the code
-Add more accurate checks (eg. compare to actual number of roadmaps instead of >0 etc.)
-Take roadmap id's into account when checking whether update/delete worked so we can be sure that correct roadmaps change.
-Some code cleanup
I also added property `roadmaps!: Roadmap[]` to user so I could access their roadmaps. Is this fine or should there be another way?
Few questions:
-Do we need to add permission tests in GET and POST?
-Do we need to check if API and DB update or is one enough? Example of updating both in: `PATCH /roadmaps/:roadmapId - Should patch roadmap`
> Refactor tests

- .github/workflows/main.yml
The current tests only test the server, so it is unnecessary (and also misleading) to run those on frontend changes.
The only benefit from running tests each time is that brittle tests are more likely noticed.
> Skip server tests on frontend-only changes

- frontend/src/components/CustomerListTable.tsx
- frontend/src/components/TableCustomerRow.tsx
- frontend/src/i18/english.ts
- frontend/src/pages/PlannerWeightsPage.tsx
- frontend/src/redux/roadmaps/index.ts
- frontend/src/redux/roadmaps/reducers.ts
- frontend/src/redux/roadmaps/selectors.ts
- frontend/src/redux/roadmaps/types.ts
- frontend/src/utils/CustomerUtils.ts
- frontend/src/utils/SortCustomerUtils.ts
- frontend/src/utils/TaskUtils.ts
Since only admins see the planner page and only few might be present in a roadmap, the edition of user weights is saved instantaneously.
> Remove local planner weights

- frontend/src/components/PlannerChart.tsx
- frontend/src/pages/MilestonesEditor.tsx
https://trello.com/c/W4z9ecJG/317-task-priority-sorting-is-inverted
> Fix bug: Task priority sorting is inverted

- server/src/api/integration/integration.model.ts
- server/tests/customer.test.ts
The private key is only needed to be sent from the frontend for adding
or updating. There is no reason to send it back.
Otherwise the private key would be visible to all the admins in the roadmap.
> Remove privatekey from integration response

- server/src/api/invitations/invitations.controller.ts
- server/src/api/invitations/invitations.model.ts
- server/src/api/invitations/invitations.routes.ts
- server/src/api/users/users.controller.ts
- server/src/migrations/20211021141414_addTimestampAndUniqueConstraintToInvitations.ts
- server/src/utils/date.ts
- Add timestamp and unique constraint (combination of roadmapId & email) to invitations
- Add route for getting invitations
> Rework invitations backend

- frontend/package.json
- frontend/src/components/EditableText.module.scss
- frontend/src/components/EditableText.tsx
- frontend/src/components/Overview.module.scss
- frontend/src/components/Overview.tsx
- frontend/src/components/forms/SvgButton.tsx
- frontend/src/pages/TaskOverviewPage.tsx
- frontend/yarn.lock
A reusable component out of the editable text implemented in TaskOverview. Mostly made with the coming Profile page rework in mind.
Both a very narrowly controllable text field with edit/close/confirm buttons, and a more freely customisable field without buttons.
> Editable text component

- frontend/src/i18/english.ts
- frontend/src/pages/TaskMapPage.module.scss
- frontend/src/pages/TaskMapPage.tsx
- frontend/src/shared.scss
Added info-icon next to the center-map icon in Task map. Info text currently gives tips about deleting relations.
> Add info icon to taskmap

- frontend/src/api/api.tsx
- frontend/src/components/TaskMapEdge.tsx
- frontend/src/pages/TaskMapPage.tsx
- frontend/src/redux/roadmaps/actions.ts
- frontend/src/redux/roadmaps/index.ts
First version of relation deleting. Currently there's two ways to delete a relation: right clicking an edge or hovering over it and pressing backspace or delete.
There will be additional features added to deleting relations but this is enough currently. The rest of the features will be added after automatic layout generator has been implemented, that will give us more info how things should work.
> Add functionality for removing task relations through task-map

- frontend/src/components/BlockGraph.module.scss
- frontend/src/components/BlockGraph.tsx
- frontend/src/components/TaskValueCreatedVisualization.module.scss
- frontend/src/components/TaskValueCreatedVisualization.tsx
- frontend/src/pages/RoadmapGraphPage.module.scss
- frontend/src/pages/RoadmapGraphPage.tsx
At the moment this scrolls the selected element into view, but that does not work when synchronising the two views on /planner/graph page. Well, it would without 'smooth' scroll, but then it doesn't feel nice.
> Block timeline

- frontend/src/pages/TaskOverviewPage.tsx
The fix was implemented earlier, but it got lost in the rebase.
> Fix bug with EditableText not closing on task change

- frontend/src/components/EditableText.tsx
- frontend/src/components/Overview.module.scss
- frontend/src/components/forms/FormField.tsx
- Used the common form field component for displaying the error.
- Added a little gap between the columns to keep those from overlapping
with the edit field border.
- The text field is focused when moving to edit mode. (The focus leaves
the cursor at the start.)
Alternative for #195
> Retain edited text on error

- frontend/src/components/RoadmapSelectorWidget.tsx
- frontend/src/pages/ProjectOverviewPage.tsx
- frontend/src/pages/TaskMapPage.tsx
- frontend/src/redux/roadmaps/index.ts
- frontend/src/redux/roadmaps/reducers.ts
- frontend/src/redux/roadmaps/selectors.ts
- frontend/src/redux/roadmaps/types.ts
Position (x, y -coordinates and zoom level) is saved to redux.
Taskmap's position is cleared when project overview is opened or roadmap is selected from the dropdown
- clearing the position on SELECT_CURRENT_ROADMAP was not suitable as it is run in every reload
> Save taskmap's position

- frontend/src/components/TopBar.module.scss
- frontend/src/components/modals/ImportTasksModal.tsx
Didn't find a way to grow the modal conveniently to fit the opened list. However, attaching the list to the document body instead of the modal allows it to go over the boundaries of the modal window such that it is visible and usable.
Also small visual fix on the task page top bar buttons.
> Fix import modal dropdown

- frontend/src/utils/requirelogin.tsx
When joining a roadmap and not logged in, redirect to register page
rather than login page.
> Fix join redirect

- frontend/src/redux/roadmaps/types.ts
- frontend/src/utils/TaskRelationUtils.ts
bugfix: https://trello.com/c/zbLbvSlK/369-task-map-hajoaa-jos-lis%C3%A4%C3%A4t-task-tablesta-uuden-taskin-ja-sitten-avaat-task-map-v%C3%A4lilehden
- Relations can be undefined
> Fix task relations type

- frontend/src/api/api.tsx
- frontend/src/components/NavBar.tsx
- frontend/src/components/forms/StepForm.tsx
- frontend/src/components/modals/JoinLinkInvalidModal.tsx
- frontend/src/components/modals/JoinLinkNoAccessModal.tsx
- frontend/src/components/modals/JoinProjectModal.tsx
- frontend/src/components/modals/ModalRoot.tsx
- frontend/src/components/modals/types.ts
- frontend/src/i18/english.ts
- frontend/src/icons/alert_orange_icon.svg
- frontend/src/pages/JoinRoadmapPage.tsx
- frontend/src/pages/LogoutPage.tsx
- frontend/src/pages/ProjectOverviewPage.tsx
- frontend/src/redux/roadmaps/actions.ts
- frontend/src/redux/roadmaps/index.ts
- frontend/src/redux/roadmaps/types.ts
- frontend/src/redux/user/actions.ts
- frontend/src/redux/user/index.ts
- frontend/src/redux/user/reducers.ts
- server/src/api/invitations/invitations.model.ts
- server/src/api/users/users.controller.ts
- server/src/api/users/users.routes.ts
https://trello.com/c/RL4FP1Up/401-figman-invitation-modaalit-fronttiin
To complete this card: https://trello.com/c/iRRBRA7S/398-handling-of-expired-invite-links-in-frontend 
I thought figma's invitation modals should be put into use. The invitation workflow is changed: first a get invitation request is sent and depending on the response a corresponding modal is opened. 
- if invitation is fetched => JoinProjectModal
- if response status is 403 => JoinLinkNoAccessModal
- other => JoinLinkUnvalidModal
User is redirected to overview page on modal close
- However, earlier the user was redirected to the new dashboard on successful project join. Opinions on whether to redirect to overview or dashboard page in this case?
> Invitation flow

- frontend/src/components/RoadmapSidebar.module.scss
- frontend/src/components/RoadmapSidebar.tsx
- frontend/src/components/modals/AddRoadmapModal.module.scss
- frontend/src/shared.scss
Previously the buttons would stretch the page vertically beyond the
viewport height, which would add extra scrollbars to the page and make
the scrolling overall a bad experience.
> Make sidebar buttons scrollable

- frontend/src/components/RoadmapSidebar.module.scss
- frontend/src/global.scss
Windows scrollbar would be annoyingly large and would stretch the sidebar on hover pushing other content to the right.
So I propose a custom scrollbar found in figma and showing it on hover. (the scrollbar is used everywhere else too though - stylistically I am not sure if it's an improvement for mac and linux users)
> Show sidebar scrollbar on hover

- server/src/api/roadmaps/roadmaps.controller.ts
- server/src/api/roadmaps/roadmaps.model.ts
- server/src/migrations/20220111090109_workTimeCalibration.ts
- server/tests/roadmaps.test.ts
Backend support for persisting a time-work calibration value that can then be used in time estimation features
> Add time-work calibration value to roadmap model

- frontend/src/components/RoadmapSelectorWidget.module.scss
Fixes a bug where roadmap-selector dropdown menu would break if the names were too long. Also improved the general look a bit and cleaned up and refactored the css file.
> Fix dropdown menu overextension

- frontend/src/api/api.ts
- frontend/src/pages/TaskMapPage.tsx
The other updates already fetched fresh roadmaps after the update, this one didn't.
The update could be more focused, e.g. only fetching the relations, but this should work fine in the meantime.
> Fix dragged task reset -bug

- frontend/src/components/CustomerListTable.tsx
- frontend/src/components/TaskTableUnrated.tsx
- frontend/src/pages/ClientOverviewPage.tsx
- frontend/src/redux/user/selectors.ts
https://trello.com/c/ayoon1PT/465-business-k%C3%A4ytt%C3%A4j%C3%A4n%C3%A4-yhden-roadmapin-omat-customerit-n%C3%A4kyy-toisessa-roadmapissa
Business users would see their customers from another roadmap in some
cases.
> Fix business users representativeFor bug

- server/tests/customer.test.ts
- server/tests/taskratings.test.ts
- server/tests/tasks.test.ts
- server/tests/testUtils.ts
Previously some tests depended on consistent order from database queries
and api responses, where no ordering was required for the tested functionality.
> Remove order dependency from tests

- frontend/src/pages/DashboardPage.tsx
For admins, all tasks missing ratings would be displayed in Dashboard's
'waiting for ratings' list.
Instead, show own missing ratings in Dashboard and all in Tasks list.
> Display only own missing ratings in Dashboard

- frontend/src/i18/english.ts
- frontend/src/utils/TaskUtils.ts
Unweighted values are used customer circles in roadmap graph page and total values in customer overview.
https://trello.com/c/eGXz6hP9/470-plan-client-weights-v%C3%A4lilehdell%C3%A4-tehdyt-valinnat-eiv%C3%A4t-tulisi-vaikuttaa-plan-roadmap-v%C3%A4lilehdell%C3%A4-olevien-asiakaspallojen-kokoon
> Use unweighted values in client visualizations

- frontend/src/components/MissingRatings.module.scss
- frontend/src/components/MissingRatings.tsx
- frontend/src/components/RatingTable.tsx
- frontend/src/components/TaskModalButtons.tsx
- frontend/src/components/TaskTable.module.scss
- frontend/src/components/TaskTableUnrated.tsx
- frontend/src/i18/english.ts
- frontend/src/pages/TaskOverviewPage.module.scss
- frontend/src/pages/TaskOverviewPage.tsx
https://trello.com/c/lDApod8t/459-task-details-n%C3%A4kym%C3%A4n-puuttuvien-ratingien-n%C3%A4ytt%C3%B6-rate-ja-notify-napit
While I was moving missing rating icons to its own component I thought to fix this too:
https://trello.com/c/ZCLnCFhR/458-puuttuvien-ratingien-ikonien-responsiivisuuden-korjaus
> Task overview rate

- frontend/src/components/modals/DeleteModal.tsx
- frontend/src/routers/RoadmapRouter.tsx
- frontend/src/utils/usePrevious.ts
I couldn't fix the edge case of another tab not navigating from /overview to /roadmap/id/dashboard if the state gets synced. Im guessing its because of checking for an existing `previousRoadmapId` before running the useEffect, but since `undefined` is a valid roadmapId (not selected) the useEffect/usePrevious cant tell the difference between the first render & intentionally null/undefined roadmap
`if (previousRoadmapId && selectedRoadmapId !== previousRoadmapId) {`
removing the check causes infinite loops and exploding galaxies. It might be fixable if we refactor our state to use `null` for intentionally nonexistent values to tell them apart from `undefined`
> Fix bug when using multiple tabs and switching roadmaps

- frontend/.eslintrc.js
- frontend/src/api/api.ts
- frontend/src/components/LoginNavBar.tsx
- frontend/src/i18/english.ts
- frontend/src/pages/ForgotPassword.module.scss
- frontend/src/pages/ForgotPasswordPage.tsx
- frontend/src/pages/LoginPage.module.scss
- frontend/src/pages/LoginPage.tsx
- frontend/src/pages/ResetPasswordPage.module.scss
- frontend/src/pages/ResetPasswordPage.tsx
- frontend/src/redux/user/actions.ts
- frontend/src/redux/user/index.ts
- frontend/src/routers/MainRouter.tsx
- frontend/src/routers/paths.ts
- frontend/src/shared.scss
- server/src/api/users/users.controller.ts
Some notes:
- Email view is currently accessible in /resetPasswordEmail/:token
- Email view still has things marked as to do since it will most likely need changes when actually implementing it to the email
- All of the pages are using old footers but I figured that creating new footers and applying it to all the other pages as well (email verification etc.) is not in the scope of this PR
> Reset password frontend

- server/src/migrations/20220208124324_fixTaskImportConstraint.ts
This adds the roadmapId to the constraint, so that the same task can be
imported to multiple roadmaps.
> Fix constraint on task table

- frontend/src/components/TaskMapEdge.module.scss
- frontend/src/components/TaskMapTask.module.scss
The custom styles were overridden by the default styles from react-flow.
This only affected production build, and has been there from the
beginning.
It would be nice to get rid of most or all the `!important`s, but this
is fine for now.
> Fix css priority in production builds

- frontend/src/components/TaskMapTask.module.scss
The addition of !important for many styles, and a min-width needed to
be matched in the .dragging styles.
> Fix dragging styles

- frontend/src/components/TaskMapTaskGroup.module.scss
- frontend/src/shared.scss
Previously the edges were in front of the task groups. Thus the edges
could obstruct a task making it unreadable. The edge's hit box is also
larger than the visual size, and can block interactions on a task below
it.
Now the edges are rendered below the task groups. The task group
background has some transparency to make it easier to see, where the
edge connects to. The existing hover effect also helps tracing an
individual edge, even if it goes under task groups.
> Move task map edges back on the z-axis

- frontend/src/components/RoleIcons.module.scss
- frontend/src/components/RoleIcons.tsx
> Warning: Failed prop type: Material-UI: `fontSize="default"` is deprecated. Use `fontSize="medium"` instead.
> Update deprecated prop type: default -> medium

- frontend/src/components/ExpandableColumn.module.scss
- frontend/src/components/ExpandableColumn.tsx
- frontend/src/components/SortableTask.module.scss
- frontend/src/components/SortableTask.tsx
- frontend/src/components/SortableTaskList.module.scss
- frontend/src/components/SortableTaskList.tsx
- frontend/src/pages/MilestonesEditor.module.scss
- frontend/src/pages/MilestonesEditor.tsx
- frontend/src/shared.scss
This improves the rendering of milestone editor page's "unordered tasks" list greatly.
From 2-3 s to expand and show the names and another ~5 s to display the ratings with 418 unordered tasks (out of 423),
to ~1 s.
> Perf sortable task list

- frontend/src/pages/PlannerWeightsPage.tsx
The rtk query made the customers jump around on updates.
This adds a consistent order to the list.
> Add consistent order to customer weights list

- frontend/src/components/SortableTaskList.tsx
- frontend/src/pages/TaskMapPage.module.scss
- frontend/src/pages/TaskMapPage.tsx
- frontend/src/utils/TaskRelationUtils.ts
This splits the tasks in task map to staged (having relations or manually added), and unstaged (all the rest) tasks.
The unstaged tasks in a list for now, but that should be simple to change.
The unstaged tasks can be staged by dragging to the task map, either individually or into existing group.
> Task map list for individual tasks

- frontend/src/components/MissingRatings.module.scss
- frontend/src/components/MissingRatings.tsx
- frontend/src/components/modals/NotifyUsersModal.tsx
- frontend/src/i18/english.ts
- frontend/src/utils/TaskUtils.ts
Waiting for ratings customer dots now show list of the users' emails. It uses really similar function as notifyUsers did, so I moved it to taskUtils and adjusted it a bit to match the needs of both
> Show missing representatives

- frontend/src/redux/user/actions.ts
- server/src/api/users/users.controller.ts
Previously the default roadmap setting failed
Additional password confirmation is only required for email and password
changes.
Also fixed/renamed what seemed like copy-paste mistake in deleteUser action.
> Fix user patching

- frontend/src/redux/index.ts
This adds a middleware that clears the state on any 401 response that
comes through the redux actions.
There are few functions in the api that are called directly. These are
obviously not handled by this middleware.
> Add middleware to check unauthenticated requests

- .github/workflows/codedeploy-staging-cd.yml
- .github/workflows/main.yml
- deployment-staging/.gitignore
- deployment-staging/.npmignore
- deployment-staging/README.md
- deployment-staging/assets/user_data.sh
- deployment-staging/bin/deployment.ts
- deployment-staging/cdk.json
- deployment-staging/jest.config.js
- deployment-staging/lib/backend-stack.ts
- deployment-staging/lib/frontend-stack.ts
- deployment-staging/package-lock.json
- deployment-staging/package.json
- deployment-staging/test/deployment.test.ts
- deployment-staging/tsconfig.json
- frontend/.eslintrc.js
- frontend/package.json
- frontend/src/components/SocketListener.tsx
- scripts/start_server
Diffi on aika ikävä koska copypastettu deployment-projekti, paikat mitä originaali deploymentistä tarvi muuttaa:
`backend-stack.ts`
Secrettien nimet eri
Load balancerilla ei saanu olla saman niminen targetGroup
`
codedeploy-staging-cd.yml`
Deployaa eri urliin, ja buildatessa eri env frontille
Deployaa eri codedeploy applikaation nimellä että se menee stagingiin
`start-server.sh`
Lukee deployment groupin nimen ja looginen branchi kummat secretit laitetaan backendin .enviin
`deployment.ts`
Eri domain yms parametrit
envVarsSecretARN osottaa eri secretiin mikä tehty käsin consolesta
(edited)
`deployment-staging/.gitignore`
poistettu .tsconfig ignoresta, jostain syystä pudotti sen tässä vaikka edellisessä toimi :thinking:
> Add CDK project for additional staging environment

- .github/workflows/frontend-ci.yml
- .github/workflows/server-ci.yml
Most pull requests only change one or the other, so it would make sense
to run only the required tests. When there are changes to the shared
files, both workflows will run.
> Separate CI-workflows for frontend and server

- frontend/src/components/TaskMap.module.scss
- frontend/src/components/TaskMap.tsx
- frontend/src/components/TaskMapTask.module.scss
- frontend/src/components/TaskMapTaskGroup.module.scss
- frontend/src/components/TaskRatingsText.module.scss
- frontend/src/pages/TaskMapPage.module.scss
- frontend/src/pages/TaskMapPage.tsx
Separates TaskMap dnd and react-flow logic. https://trello.com/c/8RGjY9As/503-improve-taskmap-code-readability
- Move ReactFlow to its own component to separate most drag-n-drop and react-flow logic.
Possible use of react-flow's useZoomPanHelper-hook is taken into consideration in this decision.
(useZoomPanHelper provides utility functions for react-flow's viewport, could be used to move canvas on drag)
useZoomPanHelper needs to be inside context of ReactFlowProvider and being a hook, it needs to be used in a component.
- Also encountered the taskmap edge-render bug again (moving a task to another group and the edges not updating correctly). Added the old fix back in.
> Taskmap refactor

- frontend/src/components/TaskMapTask.module.scss
- frontend/src/components/TaskMapTaskGroup.module.scss
I had trouble with implementing cursor: not-allowed on unavailable tasks/groups. It seemed to work only sometimes and persist when leaving to hover elsewhere.
I ended up only fixing the incorrectly shown loading cursor when dragging. I'll leave the not-allowed cursor as a separate task.
> Fix loading cursor on task drag

- frontend/src/components/TableTeamMemberRow.tsx
- frontend/src/components/TeamMemberListTable.tsx
- frontend/src/utils/SortRoadmapUserUtils.ts
- frontend/src/utils/TaskUtils.ts
Previously the row displayed the count of tasks filtered by `isUnrated`, effectively displaying the # of unrated tasks missing from representatives (the count that is used in PO's dashboard and tasklist) instead of the count of the tasks unrated specifically by the PO themself.
> Correctly display unrated tasks count in team members list

- frontend/src/pages/TaskListPage.tsx
With the new search field component, the search phrase is always
lowercase. This made it impossible to find words with non-lowercase
letters.
> Fix task list search

- frontend/src/components/RatingTable.tsx
- frontend/src/components/RatingTableComplexity.tsx
- frontend/src/components/RatingTableValue.tsx
- frontend/src/i18/english.ts
Fixes the handling of ratings user has given for a customer the user no longer represents.
Correctly shows ratings from users that have left the roadmap.
Ratings for a customer are already deleted, as they should, when the associated customer is deleted.
Todo for another issue: decide what should happen to ratings when the associated user account is deleted.
> Customer ratings without user or with old representatives

- frontend/src/components/forms/StepForm.tsx
Fix bug: if user presses "No, go back" in the cancel confirmation, the
application would crash due to a missing undefined check.
> Fix StepForm bug

- server/src/migrations/20220310110218_nullableUserReferenceInTaskrating.ts
This changes `onDelete` from `CASCADE` to `SET NULL` for `createdByUser`
foreign key, allowing ratings to remain when the user account is
deleted.
This also adds unique constraint for developer ratings, which were
previously not checked, as one column (`forCustomer`) on the index was
always NULL.
> Make taskrating's user reference nullable

- frontend/src/components/modals/EditCustomerModal.tsx
The new user info was fetched too early immediately after starting the
patch query. Now the fresh user info is fetched only after the patch has
succeeded.
> Fix user update after editing a customer

- frontend/src/components/TaskMapTask.module.scss
- frontend/src/components/TaskMapTask.tsx
https://trello.com/c/nTXYc0AF/365-task-map-handleihin-onclick-hoverille-effektit
It looks like this may be a expired task. If this is not an improvement, lets close the pr
- Add hover effect to handles (the same effect is preserved when user starts connecting from the handle)
- Unconnectable handles are grayed out
- Connectable handles have a hover effect
> Add taskmap handle style effects

- frontend/src/pages/LandingPage.tsx
Small fix. Time estimation was written twice in the feature-list.
> Fixed some text in landingpage

- frontend/src/components/EditableText.module.scss
- frontend/src/components/Overview.module.scss
- frontend/src/components/RoadmapCompletionMeter.tsx
- frontend/src/components/TaskMapTask.tsx
- frontend/src/components/TaskRelationTable.tsx
- frontend/src/components/TaskTable.module.scss
- frontend/src/components/TaskTableRated.tsx
- frontend/src/i18/english.ts
- frontend/src/pages/TaskOverviewPage.tsx
- frontend/src/redux/roadmaps/types.ts
- frontend/src/utils/TaskUtils.ts
- server/src/api/tasks/tasks.controller.ts
- server/src/api/tasks/tasks.model.ts
- server/src/migrations/20220310091901_integrationsRework.ts
- server/src/seeds/testdata.ts
- server/src/utils/socketIoUtils.ts
- server/tests/tasks.test.ts
- shared/types/customTypes.ts
- Add task status enum to replace "completed" boolean.
- Add trellomappings table to store mappings for an integration from trello column names to task statuses
- Add tokenId column to integrations to reference a token that is to be used during imports using said integration
- Add nullable trelloTableId column to integrations to reference a table name that is to be used during imports from trello
> Task status & trello board mapping schema

- server/src/api/invitations/invitations.controller.ts
- server/src/utils/typeValidation.ts
When an empty representatives array was provided, the query would fail.
Also added a bit more type validation.
> Don't perform empty query

- frontend/src/i18/english.ts
- frontend/src/pages/MilestonesEditor.module.scss
- frontend/src/pages/MilestonesEditor.tsx
If no milestones have tasks, display a drag-n-drop info message in all milestones.
The branch name is a bit outdated, it was decided that all milestones should have the instruction in this case.
> Add drag-n-drop instructions to MilestonesEditor

- frontend/src/pages/ForgotPasswordPage.tsx
- frontend/src/shared.scss
Links retain their color when being hovered over.
> Unify link stylings

- frontend/src/components/modals/JoinProjectModal.tsx
New roadmap would not appear in the list after accepting an invitation.
Now roadmaps are refetched on acception.
> Fix roadmap updation on invitation acception

- frontend/src/components/TaskTableRated.tsx
- frontend/src/components/TaskTableUnrated.tsx
- frontend/src/pages/TaskOverviewPage.tsx
- frontend/src/routers/paths.ts
Pressing F5 on task overview page previously redirected to a 404 because the page did not wait for loading first.
Also changed path to /tasks/taskid instead of /tasks/task/taskid
> Fix task overview route and 404 redirect

- frontend/src/components/modals/RateTaskModal.tsx
When user had given multiple ratings in the modal, only the latest would get appended to the request.
This was due to a wrong variable used in onBusinessRatingChange event handler. Now all changed ratings are appended to the request.
> Fix multi-rating bug

- frontend/src/components/MilestoneRatingsSummary.module.scss
- frontend/src/components/SortableTaskList.module.scss
- frontend/src/pages/MilestonesEditor.module.scss
- frontend/src/pages/MilestonesEditor.tsx
Milestones now fill the (vertical) space available for them.
This fixes the problem of too short milestone task lists. It was caused by AutoSizer, which does not stretch content
> Fix milestone styles

- frontend/src/components/TaskRelationTable.tsx
- server/src/api/tasks/tasks.controller.ts
The link path was changed a while ago. Perhaps the new path was lost in some conflict
> Fix taskrelation link path

- frontend/src/components/EditableText.tsx
- frontend/src/components/Overview.tsx
Before, user could not add newlines to the EditableText box.
Now newlines can be added with the enter-key and the field can be submitted with shift + enter.
- Added multiline prop, because EditableText is used in email field (user info page) where multiple lines are not desired.
I am not actually sure if it's more common to submit on enter or shift + enter. Can switch the logic around if needed.
> Submit multiline EditableText on shift + enter

- server/src/api/integration/integration.controller.ts
- server/src/api/tokens/tokens.model.ts
- server/src/migrations/20220328112527_fixIntegrationTokenForeignKey.ts
- server/src/utils/errorhandler.ts
I totally missed this one when reviewing the migration.
The token now has nullable foreign key to integration, since each oauth needs two entries in token table.
Also fixed the status code for invalid integration tokens, which was unpleasantly broken after we added the middleware for 401 (unauthorised) responses.
> Fix integration token foreign key

- frontend/src/components/TaskRelationTable.module.scss
- frontend/src/components/TaskRelationTable.tsx
- frontend/src/i18/english.ts
- frontend/src/pages/TaskOverviewPage.tsx
- server/src/api/taskrelation/taskrelation.routes.ts
- server/src/migrations/20220328122849_BusinessAndDeveloperUsersEditRelations.ts
- shared/types/customTypes.ts
https://trello.com/c/QG9uK4c6/576-taskin-relaatioiden-editointi-n%C3%A4kyy-kaikille-k%C3%A4ytt%C3%A4jile-overviewss%C3%A4
- Task relation edit mode is always kept open
- Taskrelation routes are made accessible to all users
- EditRelations permission is added to Developer and Business RoleTypes.
It is used in taskrelation-routes in place of (Permission.TaskRead | Permission.RoadmapEdit)
> Fix relation overview edit

- frontend/src/components/RoadmapSidebar.tsx
- frontend/src/routers/RoadmapRouter.tsx
Roadmaprouter used to show "Roadmap not found" instead of properly redirecting when roadmap was not defined. Now it properly tries to load a roadmap first and redirects to 404 if it doesnt find it.
Sidebar is also hidden now unless a valid roadmap is open.
> Hide sidebar when roadmap invalid and redirect properly

- frontend/src/api/api.ts
- frontend/src/components/RatingTable.tsx
- frontend/src/components/TaskModalButtons.tsx
- frontend/src/components/modals/AddTaskModal.tsx
- frontend/src/components/modals/RateTaskModal.tsx
- frontend/src/components/modals/types.ts
- frontend/src/pages/TaskOverviewPage.tsx
- server/src/api/tasks/tasks.controller.ts
Rate task modal tried to apply task ratings to the businessValueRatings state before fetching task correctly. This only happened when you tried giving ratings from the task modal that opens automatically after creating a new task.
I changed the parameters from TaskId to Task, this way the task can't be either loading or undefined.
> Fix RateTaskModal loading issue.

- frontend/src/components/RoadmapOverview.tsx
- frontend/src/components/RoadmapSidebar.tsx
- frontend/src/pages/MilestonesEditor.tsx
- frontend/src/pages/RoadmapGraphPage.tsx
- frontend/src/pages/TimeEstimationPage.tsx
Skip version queries if logged in user does not have permssion to query versions
(this used to create a failed query with status 403 every time certain components rendered on non-admins)
Skip roadmapsidebar roadmaps query if there is no logged in user
(this used to spam failed queries on login page)
> Query fixes

- frontend/src/components/NavBar.tsx
- frontend/src/components/TableCustomerRow.tsx
- frontend/src/components/TaskMapEdge.tsx
- frontend/src/components/TaskRelationTable.tsx
- frontend/src/components/modals/AddCustomerModal.tsx
- frontend/src/components/modals/AddTaskModal.tsx
- frontend/src/components/modals/AddTeamMemberModal.tsx
- frontend/src/components/modals/AddVersionModal.tsx
- frontend/src/components/modals/EditCustomerModal.tsx
- frontend/src/components/modals/EditTeamMemberModal.tsx
- frontend/src/components/modals/EditVersionModal.tsx
- frontend/src/components/modals/ImportTasksModal.tsx
- frontend/src/components/modals/RateTaskModal.tsx
- frontend/src/pages/ClientOverviewPage.tsx
- frontend/src/pages/ConfigurationPage.tsx
- frontend/src/pages/MilestonesEditor.tsx
- frontend/src/pages/NotFoundPage.tsx
- frontend/src/pages/PlannerWeightsPage.tsx
- frontend/src/redux/roadmaps/index.ts
- frontend/src/redux/roadmaps/reducers.ts
- frontend/src/redux/roadmaps/selectors.ts
- frontend/src/redux/roadmaps/types.ts
- frontend/src/routers/RoadmapRouter.tsx
- frontend/src/utils/SortCustomerUtils.ts
- frontend/src/utils/SortRoadmapUserUtils.ts
- frontend/src/utils/UserUtils.ts
https://trello.com/c/kbrJoN6F/520-fix-404-sivun-tyylit-kun-roadmap-on-auki
Made roadmapId nullable, also made 404 page deselect roadmap in order to hide sidebar as the trello card proposed. Returning to a previously valid roadmap still works with the browsers back button.
> Make selectedRoadmapId nullable, set to null on 404

- frontend/src/components/EditableText.module.scss
- frontend/src/pages/TaskOverviewPage.tsx
For example, "format: 'multiline'" can be passed to data in overviews.
https://trello.com/c/wMOi6X6N/598-taskoverview-description-render%C3%B6i-newlinet
> Add format for multiline text in EditableText

- frontend/src/pages/ClientOverviewPage.tsx
- frontend/src/pages/TaskOverviewPage.tsx
Client and task overview pages routed to 404 on reload. This was due to delay in fetching the chosenRoadmapSelector.
To fix the problem, the page components can show a waiting indicator while the roadmapId is undefined or null. This is possible, since RoamapRouter handles setting the chosenRoadmapId and routing to 404 if it does not exist.
> Fix 404-routing of reload of some overview pages

- frontend/src/pages/RoadmapGraphPage.module.scss
The graph did not always take up all of the available space, as seen in the picture
> Fix roadmapGraph styles

- frontend/src/api/api.ts
- frontend/src/components/RatingBars.tsx
- frontend/src/components/modals/RateTaskModal.tsx
- server/src/api/taskratings/taskratings.controller.ts
- server/src/api/taskratings/taskratings.routes.ts
- server/tests/taskratings.test.ts
Add the possibility to clear ratings in the taskrating modal by re-clicking the current rating
- If the modal is in edit-mode, the cleared rating will be deleted
- Otherwise, the cleared rating is not sent on submit
Taskrating deletion is added to the patch-route to handle everything in one transaction
- If the rating value is zero, it is deleted in the patch-route
- PatchTaskratings is renamed to updateRaskratings
> Clear taskrating

- frontend/src/components/SortableTaskList.tsx
The dragged task was taken from the full list, not the searched one.
> Fix SortableTaskList drag bug on search

- frontend/src/components/TaskMap.tsx
When trying to drag the last task from taskmap canvas to unstaged tasks -list, it was be displayed on both unstaged tasks and task map canvas as the tasks groups didn't update (TaskRelations.length === 0 in that case and the useEffect that creates the groups didn't run)
https://trello.com/c/PI0VbFax/613-kun-viimeinen-task-raahataan-kartasta-listaan-siirtyy-listaan-ja-n%C3%A4kyy-edelleen-kartassa
> Fix stagedTasks visual bug in task map

- frontend/src/components/UserInfoCard.module.scss
- frontend/src/components/UserInfoCard.tsx
- frontend/src/components/forms/FormField.module.scss
- frontend/src/components/forms/FormField.tsx
- frontend/src/components/modals/ChangePasswordModal.module.scss
- frontend/src/components/modals/ChangePasswordModal.tsx
- frontend/src/components/modals/ModalRoot.tsx
- frontend/src/components/modals/types.ts
- frontend/src/i18/english.ts
- frontend/src/routers/MainRouter.tsx
So I made the change password modal that is in style with whats on Figma (except for those toggles that let you see passwords in cleartext. Should i make a new task in Trello to add those in this modal and maybe to ResetPassword modal?)
With this change, that EditableTextWithButtons don't really make sense to me. 
Should this just be some kind of a button that opens the modal? I temporarily used linkButton for the functionality.
> Add confirmation to change password

- frontend/src/components/RatingTable.module.scss
- frontend/src/components/RatingTable.tsx
- frontend/src/components/RatingTableComplexity.tsx
- frontend/src/components/RatingTableValue.tsx
- frontend/src/components/modals/ModalRoot.tsx
- frontend/src/components/modals/RemoveRatingModal.tsx
- frontend/src/components/modals/types.ts
- frontend/src/i18/english.ts
- frontend/src/routers/MainRouter.tsx
User with Permission.TaskRatingEditOthers (so admin) can delete any ratings from task overview page.
Adds delete-icons to task overview page and upon clicking them it opens a modal to confirm the deletion.
> Add delete buttons for task ratings

- frontend/src/components/forms/SvgButton.module.scss
- frontend/src/components/forms/SvgButton.tsx
- frontend/src/pages/MilestonesEditor.tsx
- frontend/src/shared.scss
Any buttons that open a modal are disabled while versions are patched in MilestonesEditor.
- Loading cursor is applied to the whole milestone and expandable task list
> Disable MilestonesEditor features while loading

- frontend/src/components/RoadmapGraphSidebar.tsx
- frontend/src/components/RoadmapSidebar.tsx
- frontend/src/components/SortableTask.tsx
- frontend/src/components/SortableTaskList.tsx
- frontend/src/pages/MilestonesEditor.tsx
- frontend/src/pages/RoadmapGraphPage.tsx
- frontend/src/routers/PlannerPageRouter.tsx
- server/src/migrations/20220420080810_addPermissionVersionReadToBusinessRole.ts
- shared/types/customTypes.ts
Planner is accessible in read mode to users with Permission.VersionRead.
- Developer or business -users do not have Permission.RoadmapReadCustomerValues, so in those cases the customer weights page is hidden and unweighted milestone values is used
- Add VersionRead-permission to business role
> Planner read-mode

- frontend/src/components/CustomerWeightsVisualization.module.scss
- frontend/src/components/CustomerWeightsVisualization.tsx
- frontend/src/components/PercentageBar.module.scss
- frontend/src/components/PercentageBar.tsx
- frontend/src/components/RoadmapGraphSidebar.tsx
- frontend/src/components/TaskValueCreatedVisualization.module.scss
- frontend/src/components/TaskValueCreatedVisualization.tsx
- frontend/src/i18/english.ts
- frontend/src/pages/MilestonesEditor.module.scss
- frontend/src/pages/MilestonesEditor.tsx
- frontend/src/pages/RoadmapGraphPage.tsx
- frontend/src/shared.scss
Refactored PercentageBar to its own component, adjusted interface of components for more flexibility (stakes visualization accepts an array of versions instead of just one)
Relocated the info icon to the topbar, it was looking weirdly out of place with the original absolute positioning, and I felt it was easier to notice up in the topbar
Currently the stakes visualization calculates the stakes for all roadmaps milestones, milestone selection is in another card and this component shall be updated then to only use the selected milestones.
> Add topbar with visualizations to milestone planner

- frontend/src/components/EditableText.tsx
The multiline property was never provided. Changed now so that multiline format implies multiline editing (when editable)
> Add back multi line input

- frontend/src/components/SortableTask.module.scss
- frontend/src/components/SortableTask.tsx
- frontend/src/components/SortableTaskList.tsx
- frontend/src/pages/MilestonesEditor.module.scss
Changes the variable size list to a fixed size one.
Each task is given enough room for two lines of text. This is much snappier for many hundreds of tasks.
The magic numbers should be refactored.
> POC: Variable size list to fixed size

- frontend/src/components/TaskMap.tsx
- frontend/src/components/TaskMapTask.module.scss
- frontend/src/components/TaskMapTaskGroup.module.scss
- frontend/src/components/TaskMapTaskGroup.tsx
- frontend/src/pages/TaskMapPage.tsx
Previously dropping a task on an unavailable group would count as dropping the task on the canvas (removing the task from the group). Now the drop gets cancelled instead and nothing happens.
> Cancel drag and drop when dropping task to unavailable groups

- frontend/src/pages/MilestonesEditor.tsx
The `tasks` could be `undefined` in some circumstances, which lead to
silent failure in lookup from `tasksById`, and a crash later in the
page.
Repro of the error:
- navigate to `/roadmap/1/planner/graph`
- refresh the page
- select the `milestones` tab
- page crashes
> Fix crash on missing tasks in milestone editor

- frontend/src/components/TaskRelationTable.tsx
This makes the task overview consistent with the behaviour in task map.
Previously synergies were added between individual tasks, not taking
account possible existing synergy group.
Now when adding a synergy, the relation is also added for each task
already in synergy with the edited task.
> Make synergy editing behave consistently in task overview

- frontend/src/components/MilestonesAmountSummary.tsx
planner/graph page doesn't yet indicate the "in progress" state of milestones, but planner/editor does, so added this now
> Only consider started milestones to be in progress

- frontend/src/components/SortableTask.tsx
- frontend/src/components/TaskRelationTable.tsx
- frontend/src/components/TaskTable.module.scss
- frontend/src/components/TaskTable.tsx
- frontend/src/components/modals/RelationsModal.module.scss
- frontend/src/components/modals/RelationsModal.tsx
- frontend/src/components/modals/types.ts
- frontend/src/pages/MilestonesEditor.tsx
- frontend/src/pages/RoadmapGraphPage.module.scss
- frontend/src/routers/MainRouter.tsx
- frontend/src/shared.scss
Showing the relations in a drawer in the side instead of modal that would block the rest of the page.
I'm maybe abusing the modal link system a bit, but it works.
There is an extra horizontal scroll bar when the drawer is closed for some reason, don't yet know why.
> Planner relation modal in drawer

- frontend/src/components/SortableTaskList.tsx
- frontend/src/pages/TaskMapPage.tsx
Not sure if this was intentionally left out from #406, but I now removed the ratings from the unstaged list too.
Also removed the search threshold from the task list, as that is fast enough.
> Task map - remove remaining ratings

- frontend/src/routers/paths.ts
It hasn't been once or twice when I've had to peek into the definition
to see if I should add a separator or not.
This enforces a consistent format for the defined segments:
- segment must start with the separator
- segment must not end with the separator, unless it consist only of the
separator
The format as a regular expression:
/|/.*[^/]
This also provides literal types for the segments, making it easier to
look up the value when necessary.
Also removed one unused duplicate definition.
> Add sanity check and better typing for paths

- frontend/src/api/api.ts
- frontend/src/components/Overview.tsx
- frontend/src/i18/english.ts
- frontend/src/pages/ConfigurationPage.module.scss
- frontend/src/pages/ConfigurationPage.tsx
Takes advantage of overviewContent. Not necessarily in align with the look of the settings-page, but gets the job done.
> Add edition for roadmap name and description

- frontend/src/components/TaskMap.tsx
- frontend/src/components/TaskMapTask.module.scss
- frontend/src/pages/TaskMapPage.tsx
The portal containing dragged tasks was attached to TaskMapPage, where zoom level was not in scope. This lead to broken dragging styles.
After the correction, most dragging styles are fixed. However, Handle's border-width remains broken for unknown reasons.
> Correct TaskMap portal creation

- frontend/src/components/RatingTable.tsx
- frontend/src/components/RatingTableComplexity.tsx
- frontend/src/components/RatingTableValue.tsx
Default sorting for complexity-table is creator instead of the customer.
Only solves part of the problem: customer is still selectable as sorting, which is useless for complexity-table. I made [a card about that](https://trello.com/c/CopQGUnQ/696-taskoverview-poista-customer-sort-vaihtoehto-complexity-rating-tablesta).
> Add default sort prop to RatingTable

- frontend/src/components/RatingTable.module.scss
- frontend/src/components/RatingTableComplexity.tsx
- frontend/src/components/RatingTableValue.tsx
- frontend/src/i18/english.ts
- frontend/src/utils/SortRatingsUtils.ts
- frontend/src/utils/SortUtils.ts
- frontend/src/utils/string.ts
Also removed uses of deprecated `String.prototype.substr()`
> Rating value sort highest/lowest value

- frontend/src/components/modals/InfoModal.module.scss
- frontend/src/i18/english.ts
- frontend/src/pages/TimeEstimationPage.module.scss
- frontend/src/pages/TimeEstimationPage.tsx
- frontend/src/utils/TaskUtils.ts
Completed milestones are not available in the comparison.
Completed tasks are not counted in the estimation results.
The new workflow would be:
1. Select a milestone
2. Estimate how long the whole milestone would take, regardless of current progress
3. Get a time estimation result. Selected milestone days estimation may be shorter than in step 2, if any tasks are completed.
> Consider TaskStatus in TimeEstimationPage

- frontend/src/components/IntegrationConfiguration.module.scss
- frontend/src/i18/english.ts
- frontend/src/pages/ConfigurationPage.module.scss
- frontend/src/pages/ConfigurationPage.tsx
https://trello.com/c/34SGwwTr/694-setting-sivun-yleisilme-siistimm%C3%A4ksi
Since a strict design was missing, the I tried a layout reminiscent of user info or overview pages. Patric also experimented with side-by-side integrations, which seems nice
Not sure if the `margin-top: auto;` looks best with the delete button: opinions are welcome.
As a note, there is [a separate card for configuration styles](https://trello.com/c/Up1B94vI/698-setting-configuration-tyylit-figman-mukaiseksi).
> Add more elaborate settings-page styles

- frontend/src/pages/TimeEstimationPage.tsx
Empty milestones are excluded from the dropdown. 
If all milestones are empty, show a empty dropdown with "No milestones available" message.
> Consider empty milestones in TimeEstimationPage

- server/src/utils/socketIoUtils.ts
Websocket refresh only worked if you refreshed the page while you had a roadmap selected - socket communication relies on users being added in rooms corresponding to their userId when they connect, and the server was making them leave those rooms when no roadmap was selected.
> Fix having to refresh for sockets to work

- frontend/src/pages/MilestonesEditor.tsx
Showing both felt quite cramped, so I just left out the ratings as those are also found in the tooltip.
The disadvantage is that it's no longer easy to look through all the tasks in the list, as one must open the tooltip first.
For that some indication of the important tasks could be useful, so the user knows which tooltips to check.
> Show info for unordered tasks

- frontend/src/shared.scss
TopBar was shrinking too much with (really) small screen width and contents of the TopBar overflowed, setting min-width: min-content for .topBar fixes the issue
> Fix topbar shrinking behaviour

- frontend/src/components/BlockGraph.tsx
The items would not be displayed at all if all the values were the same.
Thus a single milestone would never be shown.
> Fix graph sizing bug

- frontend/src/components/MissingRatings.module.scss
- frontend/src/components/MissingRatings.tsx
- frontend/src/components/TaskTable.module.scss
- Limited the task list page titles to 2 lines, and added bit more line height.
- The rating tooltip text overflow is now hidden (using `ellipsis` to give some indication that the full email isn't shown)
> Fix text overflows

- frontend/src/pages/MilestonesEditor.module.scss
- frontend/src/pages/MilestonesEditor.tsx
Now the topbar section is independently scrollable and there should be only one horizontal bar at the bottom.
Also added larger minimum height for the milestones, as the content
would overflow on the previous minimum.
> Remove unnecessary scrollbars on milestone editor page

- frontend/src/components/MissingRatings.module.scss
The column has room for minimum of 6 dots.
Showing the number of hidden dots might be "nice to have" option, but I'm not sure if that would be reasonable to implement.
> Hide overflowing "waiting for ratings" dots

- frontend/src/components/modals/LeaveRoadmapModal.tsx
- frontend/src/redux/roadmaps/actions.ts
Fixes two things related to leaving a roadmap:
1. If the same roadmap was selected, unselect the roadmap
2. Refetch roadmaps (RoadmapSelectorWidget was not updated after
leaving a roadmap)
> Fix leave roadmap

- frontend/src/routers/PlannerPageRouter.tsx
- frontend/src/routers/RoadmapRouter.tsx
- frontend/src/utils/requirelogin.tsx
https://trello.com/c/7zZHCnY1/681-lis%C3%A4%C3%A4-route-authorization
RequireRole and requirePermission can be used in roadmap routes to require a certain role or permission in order to access the route. If the condition is not met, user is redirected to 404 page.
> Add route authorization

- frontend/src/utils/requirelogin.tsx
Roadmap role can be undefined when reloading the page, which was not considered in the requirePermission or requireRole functions.
> Fix routing to 404 on roadmap page reload

- frontend/src/components/modals/VersionDetailsModal.tsx
- frontend/src/components/modals/types.ts
- frontend/src/pages/MilestonesEditor.tsx
- frontend/src/pages/PlannerWeightsPage.tsx
- frontend/src/pages/RoadmapGraphPage.tsx
One client always has 100% of "produced" values, so there is no need to show visualizations related to it
> Hide shares visualizations with only one client

- frontend/src/components/modals/TaskMapInfoModal.tsx
- frontend/src/components/modals/modalparts/TaskMapInfoModalColumns.tsx
The mapped divs were missing keys. I added a custom key to each object in `TaskMapInfoModalColumns.tsx`. Decided to go for this solution as you couldn't use the FC nor Translation elements directly as the key.
> Add keys to columns in task map info-modal
